// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/Tron.proto

package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AccountType int32

const (
	AccountType_Normal     AccountType = 0
	AccountType_AssetIssue AccountType = 1
	AccountType_Contract   AccountType = 2
)

var AccountType_name = map[int32]string{
	0: "Normal",
	1: "AssetIssue",
	2: "Contract",
}
var AccountType_value = map[string]int32{
	"Normal":     0,
	"AssetIssue": 1,
	"Contract":   2,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}
func (AccountType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type ReasonCode int32

const (
	ReasonCode_REQUESTED             ReasonCode = 0
	ReasonCode_TCP_ERROR             ReasonCode = 1
	ReasonCode_BAD_PROTOCOL          ReasonCode = 2
	ReasonCode_USELESS_PEER          ReasonCode = 3
	ReasonCode_TOO_MANY_PEERS        ReasonCode = 4
	ReasonCode_DUPLICATE_PEER        ReasonCode = 5
	ReasonCode_INCOMPATIBLE_PROTOCOL ReasonCode = 6
	ReasonCode_NULL_IDENTITY         ReasonCode = 7
	ReasonCode_PEER_QUITING          ReasonCode = 8
	ReasonCode_UNEXPECTED_IDENTITY   ReasonCode = 9
	ReasonCode_LOCAL_IDENTITY        ReasonCode = 10
	ReasonCode_PING_TIMEOUT          ReasonCode = 11
	ReasonCode_USER_REASON           ReasonCode = 16
	ReasonCode_RESET                 ReasonCode = 17
	ReasonCode_SYNC_FAIL             ReasonCode = 18
	ReasonCode_TIME_OUT              ReasonCode = 19
	ReasonCode_BAD_TX                ReasonCode = 20
	ReasonCode_BAD_BLOCK             ReasonCode = 21
	ReasonCode_FORKED                ReasonCode = 22
	ReasonCode_UNLINKABLE            ReasonCode = 23
	ReasonCode_INCOMPATIBLE_VERSION  ReasonCode = 24
	ReasonCode_INCOMPATIBLE_CHAIN    ReasonCode = 25
	ReasonCode_UNKNOWN               ReasonCode = 255
)

var ReasonCode_name = map[int32]string{
	0:   "REQUESTED",
	1:   "TCP_ERROR",
	2:   "BAD_PROTOCOL",
	3:   "USELESS_PEER",
	4:   "TOO_MANY_PEERS",
	5:   "DUPLICATE_PEER",
	6:   "INCOMPATIBLE_PROTOCOL",
	7:   "NULL_IDENTITY",
	8:   "PEER_QUITING",
	9:   "UNEXPECTED_IDENTITY",
	10:  "LOCAL_IDENTITY",
	11:  "PING_TIMEOUT",
	16:  "USER_REASON",
	17:  "RESET",
	18:  "SYNC_FAIL",
	19:  "TIME_OUT",
	20:  "BAD_TX",
	21:  "BAD_BLOCK",
	22:  "FORKED",
	23:  "UNLINKABLE",
	24:  "INCOMPATIBLE_VERSION",
	25:  "INCOMPATIBLE_CHAIN",
	255: "UNKNOWN",
}
var ReasonCode_value = map[string]int32{
	"REQUESTED":             0,
	"TCP_ERROR":             1,
	"BAD_PROTOCOL":          2,
	"USELESS_PEER":          3,
	"TOO_MANY_PEERS":        4,
	"DUPLICATE_PEER":        5,
	"INCOMPATIBLE_PROTOCOL": 6,
	"NULL_IDENTITY":         7,
	"PEER_QUITING":          8,
	"UNEXPECTED_IDENTITY":   9,
	"LOCAL_IDENTITY":        10,
	"PING_TIMEOUT":          11,
	"USER_REASON":           16,
	"RESET":                 17,
	"SYNC_FAIL":             18,
	"TIME_OUT":              19,
	"BAD_TX":                20,
	"BAD_BLOCK":             21,
	"FORKED":                22,
	"UNLINKABLE":            23,
	"INCOMPATIBLE_VERSION":  24,
	"INCOMPATIBLE_CHAIN":    25,
	"UNKNOWN":               255,
}

func (x ReasonCode) String() string {
	return proto.EnumName(ReasonCode_name, int32(x))
}
func (ReasonCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

// transcation type, utxo is desprated.
type Transaction_TransactionType int32

const (
	Transaction_UtxoType     Transaction_TransactionType = 0
	Transaction_ContractType Transaction_TransactionType = 1
)

var Transaction_TransactionType_name = map[int32]string{
	0: "UtxoType",
	1: "ContractType",
}
var Transaction_TransactionType_value = map[string]int32{
	"UtxoType":     0,
	"ContractType": 1,
}

func (x Transaction_TransactionType) String() string {
	return proto.EnumName(Transaction_TransactionType_name, int32(x))
}
func (Transaction_TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{8, 0}
}

type Transaction_Contract_ContractType int32

const (
	Transaction_Contract_AccountCreateContract         Transaction_Contract_ContractType = 0
	Transaction_Contract_TransferContract              Transaction_Contract_ContractType = 1
	Transaction_Contract_TransferAssetContract         Transaction_Contract_ContractType = 2
	Transaction_Contract_VoteAssetContract             Transaction_Contract_ContractType = 3
	Transaction_Contract_VoteWitnessContract           Transaction_Contract_ContractType = 4
	Transaction_Contract_WitnessCreateContract         Transaction_Contract_ContractType = 5
	Transaction_Contract_AssetIssueContract            Transaction_Contract_ContractType = 6
	Transaction_Contract_DeployContract                Transaction_Contract_ContractType = 7
	Transaction_Contract_WitnessUpdateContract         Transaction_Contract_ContractType = 8
	Transaction_Contract_ParticipateAssetIssueContract Transaction_Contract_ContractType = 9
	Transaction_Contract_AccountUpdateContract         Transaction_Contract_ContractType = 10
	Transaction_Contract_FreezeBalanceContract         Transaction_Contract_ContractType = 11
	Transaction_Contract_UnfreezeBalanceContract       Transaction_Contract_ContractType = 12
	Transaction_Contract_WithdrawBalanceContract       Transaction_Contract_ContractType = 13
	Transaction_Contract_CustomContract                Transaction_Contract_ContractType = 20
)

var Transaction_Contract_ContractType_name = map[int32]string{
	0:  "AccountCreateContract",
	1:  "TransferContract",
	2:  "TransferAssetContract",
	3:  "VoteAssetContract",
	4:  "VoteWitnessContract",
	5:  "WitnessCreateContract",
	6:  "AssetIssueContract",
	7:  "DeployContract",
	8:  "WitnessUpdateContract",
	9:  "ParticipateAssetIssueContract",
	10: "AccountUpdateContract",
	11: "FreezeBalanceContract",
	12: "UnfreezeBalanceContract",
	13: "WithdrawBalanceContract",
	20: "CustomContract",
}
var Transaction_Contract_ContractType_value = map[string]int32{
	"AccountCreateContract":         0,
	"TransferContract":              1,
	"TransferAssetContract":         2,
	"VoteAssetContract":             3,
	"VoteWitnessContract":           4,
	"WitnessCreateContract":         5,
	"AssetIssueContract":            6,
	"DeployContract":                7,
	"WitnessUpdateContract":         8,
	"ParticipateAssetIssueContract": 9,
	"AccountUpdateContract":         10,
	"FreezeBalanceContract":         11,
	"UnfreezeBalanceContract":       12,
	"WithdrawBalanceContract":       13,
	"CustomContract":                20,
}

func (x Transaction_Contract_ContractType) String() string {
	return proto.EnumName(Transaction_Contract_ContractType_name, int32(x))
}
func (Transaction_Contract_ContractType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{8, 0, 0}
}

type Transaction_ResultCode int32

const (
	Transaction_Result_SUCESS Transaction_ResultCode = 0
	Transaction_Result_FAILED Transaction_ResultCode = 1
)

var Transaction_ResultCode_name = map[int32]string{
	0: "SUCESS",
	1: "FAILED",
}
var Transaction_ResultCode_value = map[string]int32{
	"SUCESS": 0,
	"FAILED": 1,
}

func (x Transaction_ResultCode) String() string {
	return proto.EnumName(Transaction_ResultCode_name, int32(x))
}
func (Transaction_ResultCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{8, 1, 0} }

type BlockInventory_Type int32

const (
	BlockInventory_SYNC    BlockInventory_Type = 0
	BlockInventory_ADVTISE BlockInventory_Type = 1
	BlockInventory_FETCH   BlockInventory_Type = 2
)

var BlockInventory_Type_name = map[int32]string{
	0: "SYNC",
	1: "ADVTISE",
	2: "FETCH",
}
var BlockInventory_Type_value = map[string]int32{
	"SYNC":    0,
	"ADVTISE": 1,
	"FETCH":   2,
}

func (x BlockInventory_Type) String() string {
	return proto.EnumName(BlockInventory_Type_name, int32(x))
}
func (BlockInventory_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{12, 0} }

type Inventory_InventoryType int32

const (
	Inventory_TRX   Inventory_InventoryType = 0
	Inventory_BLOCK Inventory_InventoryType = 1
)

var Inventory_InventoryType_name = map[int32]string{
	0: "TRX",
	1: "BLOCK",
}
var Inventory_InventoryType_value = map[string]int32{
	"TRX":   0,
	"BLOCK": 1,
}

func (x Inventory_InventoryType) String() string {
	return proto.EnumName(Inventory_InventoryType_name, int32(x))
}
func (Inventory_InventoryType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{13, 0} }

type Items_ItemType int32

const (
	Items_ERR         Items_ItemType = 0
	Items_TRX         Items_ItemType = 1
	Items_BLOCK       Items_ItemType = 2
	Items_BLOCKHEADER Items_ItemType = 3
)

var Items_ItemType_name = map[int32]string{
	0: "ERR",
	1: "TRX",
	2: "BLOCK",
	3: "BLOCKHEADER",
}
var Items_ItemType_value = map[string]int32{
	"ERR":         0,
	"TRX":         1,
	"BLOCK":       2,
	"BLOCKHEADER": 3,
}

func (x Items_ItemType) String() string {
	return proto.EnumName(Items_ItemType_name, int32(x))
}
func (Items_ItemType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{14, 0} }

// AccountId, (name, address) use name, (null, address) use address, (name, null) use name,
type AccountId struct {
	Name    []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address []byte `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *AccountId) Reset()                    { *m = AccountId{} }
func (m *AccountId) String() string            { return proto.CompactTextString(m) }
func (*AccountId) ProtoMessage()               {}
func (*AccountId) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *AccountId) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *AccountId) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

// Account
type Account struct {
	AccountName []byte      `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Type        AccountType `protobuf:"varint,2,opt,name=type,enum=protocol.AccountType" json:"type,omitempty"`
	// the create adress
	Address []byte `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// the trx balance
	Balance int64 `protobuf:"varint,4,opt,name=balance" json:"balance,omitempty"`
	// the votes
	Votes []*Account_Vote `protobuf:"bytes,5,rep,name=votes" json:"votes,omitempty"`
	// the other asset owned by this account
	Asset map[string]int64 `protobuf:"bytes,6,rep,name=asset" json:"asset,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// the frozen balance
	Frozen []*Account_Frozen `protobuf:"bytes,7,rep,name=frozen" json:"frozen,omitempty"`
	// bandwidth, get from frozen
	Bandwidth int64 `protobuf:"varint,8,opt,name=bandwidth" json:"bandwidth,omitempty"`
	// this account create time
	CreateTime int64 `protobuf:"varint,9,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	// this last opration time, including transfer, voting and so on.
	LatestOprationTime int64 `protobuf:"varint,10,opt,name=latest_opration_time,json=latestOprationTime" json:"latest_opration_time,omitempty"`
	// witness block producing allowance
	Allowance int64 `protobuf:"varint,11,opt,name=allowance" json:"allowance,omitempty"`
	// last withdraw time
	LatestWithdrawTime int64 `protobuf:"varint,12,opt,name=latest_withdraw_time,json=latestWithdrawTime" json:"latest_withdraw_time,omitempty"`
	// not used so far
	Code []byte `protobuf:"bytes,13,opt,name=code,proto3" json:"code,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *Account) GetAccountName() []byte {
	if m != nil {
		return m.AccountName
	}
	return nil
}

func (m *Account) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_Normal
}

func (m *Account) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetVotes() []*Account_Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *Account) GetAsset() map[string]int64 {
	if m != nil {
		return m.Asset
	}
	return nil
}

func (m *Account) GetFrozen() []*Account_Frozen {
	if m != nil {
		return m.Frozen
	}
	return nil
}

func (m *Account) GetBandwidth() int64 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *Account) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Account) GetLatestOprationTime() int64 {
	if m != nil {
		return m.LatestOprationTime
	}
	return 0
}

func (m *Account) GetAllowance() int64 {
	if m != nil {
		return m.Allowance
	}
	return 0
}

func (m *Account) GetLatestWithdrawTime() int64 {
	if m != nil {
		return m.LatestWithdrawTime
	}
	return 0
}

func (m *Account) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

// vote message
type Account_Vote struct {
	// the super rep address
	VoteAddress []byte `protobuf:"bytes,1,opt,name=vote_address,json=voteAddress,proto3" json:"vote_address,omitempty"`
	// the vote num to this super rep.
	VoteCount int64 `protobuf:"varint,2,opt,name=vote_count,json=voteCount" json:"vote_count,omitempty"`
}

func (m *Account_Vote) Reset()                    { *m = Account_Vote{} }
func (m *Account_Vote) String() string            { return proto.CompactTextString(m) }
func (*Account_Vote) ProtoMessage()               {}
func (*Account_Vote) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 0} }

func (m *Account_Vote) GetVoteAddress() []byte {
	if m != nil {
		return m.VoteAddress
	}
	return nil
}

func (m *Account_Vote) GetVoteCount() int64 {
	if m != nil {
		return m.VoteCount
	}
	return 0
}

// frozen balance
type Account_Frozen struct {
	// the frozen trx balance
	FrozenBalance int64 `protobuf:"varint,1,opt,name=frozen_balance,json=frozenBalance" json:"frozen_balance,omitempty"`
	// the expire time
	ExpireTime int64 `protobuf:"varint,2,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
}

func (m *Account_Frozen) Reset()                    { *m = Account_Frozen{} }
func (m *Account_Frozen) String() string            { return proto.CompactTextString(m) }
func (*Account_Frozen) ProtoMessage()               {}
func (*Account_Frozen) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 1} }

func (m *Account_Frozen) GetFrozenBalance() int64 {
	if m != nil {
		return m.FrozenBalance
	}
	return 0
}

func (m *Account_Frozen) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

type Acuthrity struct {
	Account        *AccountId `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	PermissionName []byte     `protobuf:"bytes,2,opt,name=permission_name,json=permissionName,proto3" json:"permission_name,omitempty"`
}

func (m *Acuthrity) Reset()                    { *m = Acuthrity{} }
func (m *Acuthrity) String() string            { return proto.CompactTextString(m) }
func (*Acuthrity) ProtoMessage()               {}
func (*Acuthrity) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *Acuthrity) GetAccount() *AccountId {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Acuthrity) GetPermissionName() []byte {
	if m != nil {
		return m.PermissionName
	}
	return nil
}

type Permision struct {
	Account *AccountId `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *Permision) Reset()                    { *m = Permision{} }
func (m *Permision) String() string            { return proto.CompactTextString(m) }
func (*Permision) ProtoMessage()               {}
func (*Permision) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *Permision) GetAccount() *AccountId {
	if m != nil {
		return m.Account
	}
	return nil
}

// Witness
type Witness struct {
	Address        []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	VoteCount      int64  `protobuf:"varint,2,opt,name=voteCount" json:"voteCount,omitempty"`
	PubKey         []byte `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Url            string `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	TotalProduced  int64  `protobuf:"varint,5,opt,name=totalProduced" json:"totalProduced,omitempty"`
	TotalMissed    int64  `protobuf:"varint,6,opt,name=totalMissed" json:"totalMissed,omitempty"`
	LatestBlockNum int64  `protobuf:"varint,7,opt,name=latestBlockNum" json:"latestBlockNum,omitempty"`
	LatestSlotNum  int64  `protobuf:"varint,8,opt,name=latestSlotNum" json:"latestSlotNum,omitempty"`
	IsJobs         bool   `protobuf:"varint,9,opt,name=isJobs" json:"isJobs,omitempty"`
}

func (m *Witness) Reset()                    { *m = Witness{} }
func (m *Witness) String() string            { return proto.CompactTextString(m) }
func (*Witness) ProtoMessage()               {}
func (*Witness) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *Witness) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Witness) GetVoteCount() int64 {
	if m != nil {
		return m.VoteCount
	}
	return 0
}

func (m *Witness) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Witness) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Witness) GetTotalProduced() int64 {
	if m != nil {
		return m.TotalProduced
	}
	return 0
}

func (m *Witness) GetTotalMissed() int64 {
	if m != nil {
		return m.TotalMissed
	}
	return 0
}

func (m *Witness) GetLatestBlockNum() int64 {
	if m != nil {
		return m.LatestBlockNum
	}
	return 0
}

func (m *Witness) GetLatestSlotNum() int64 {
	if m != nil {
		return m.LatestSlotNum
	}
	return 0
}

func (m *Witness) GetIsJobs() bool {
	if m != nil {
		return m.IsJobs
	}
	return false
}

type TXOutput struct {
	Value      int64  `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	PubKeyHash []byte `protobuf:"bytes,2,opt,name=pubKeyHash,proto3" json:"pubKeyHash,omitempty"`
}

func (m *TXOutput) Reset()                    { *m = TXOutput{} }
func (m *TXOutput) String() string            { return proto.CompactTextString(m) }
func (*TXOutput) ProtoMessage()               {}
func (*TXOutput) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *TXOutput) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TXOutput) GetPubKeyHash() []byte {
	if m != nil {
		return m.PubKeyHash
	}
	return nil
}

type TXInput struct {
	RawData   *TXInputRaw `protobuf:"bytes,1,opt,name=raw_data,json=rawData" json:"raw_data,omitempty"`
	Signature []byte      `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *TXInput) Reset()                    { *m = TXInput{} }
func (m *TXInput) String() string            { return proto.CompactTextString(m) }
func (*TXInput) ProtoMessage()               {}
func (*TXInput) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *TXInput) GetRawData() *TXInputRaw {
	if m != nil {
		return m.RawData
	}
	return nil
}

func (m *TXInput) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type TXInputRaw struct {
	TxID   []byte `protobuf:"bytes,1,opt,name=txID,proto3" json:"txID,omitempty"`
	Vout   int64  `protobuf:"varint,2,opt,name=vout" json:"vout,omitempty"`
	PubKey []byte `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
}

func (m *TXInputRaw) Reset()                    { *m = TXInputRaw{} }
func (m *TXInputRaw) String() string            { return proto.CompactTextString(m) }
func (*TXInputRaw) ProtoMessage()               {}
func (*TXInputRaw) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6, 0} }

func (m *TXInputRaw) GetTxID() []byte {
	if m != nil {
		return m.TxID
	}
	return nil
}

func (m *TXInputRaw) GetVout() int64 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *TXInputRaw) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type TXOutputs struct {
	Outputs []*TXOutput `protobuf:"bytes,1,rep,name=outputs" json:"outputs,omitempty"`
}

func (m *TXOutputs) Reset()                    { *m = TXOutputs{} }
func (m *TXOutputs) String() string            { return proto.CompactTextString(m) }
func (*TXOutputs) ProtoMessage()               {}
func (*TXOutputs) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *TXOutputs) GetOutputs() []*TXOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type Transaction struct {
	RawData   *TransactionRaw       `protobuf:"bytes,1,opt,name=raw_data,json=rawData" json:"raw_data,omitempty"`
	Signature [][]byte              `protobuf:"bytes,2,rep,name=signature,proto3" json:"signature,omitempty"`
	Ret       []*Transaction_Result `protobuf:"bytes,5,rep,name=ret" json:"ret,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *Transaction) GetRawData() *TransactionRaw {
	if m != nil {
		return m.RawData
	}
	return nil
}

func (m *Transaction) GetSignature() [][]byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Transaction) GetRet() []*Transaction_Result {
	if m != nil {
		return m.Ret
	}
	return nil
}

type Transaction_Contract struct {
	Type         Transaction_Contract_ContractType `protobuf:"varint,1,opt,name=type,enum=protocol.Transaction_Contract_ContractType" json:"type,omitempty"`
	Parameter    *google_protobuf.Any              `protobuf:"bytes,2,opt,name=parameter" json:"parameter,omitempty"`
	Provider     []byte                            `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ContractName []byte                            `protobuf:"bytes,4,opt,name=ContractName,proto3" json:"ContractName,omitempty"`
}

func (m *Transaction_Contract) Reset()                    { *m = Transaction_Contract{} }
func (m *Transaction_Contract) String() string            { return proto.CompactTextString(m) }
func (*Transaction_Contract) ProtoMessage()               {}
func (*Transaction_Contract) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8, 0} }

func (m *Transaction_Contract) GetType() Transaction_Contract_ContractType {
	if m != nil {
		return m.Type
	}
	return Transaction_Contract_AccountCreateContract
}

func (m *Transaction_Contract) GetParameter() *google_protobuf.Any {
	if m != nil {
		return m.Parameter
	}
	return nil
}

func (m *Transaction_Contract) GetProvider() []byte {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *Transaction_Contract) GetContractName() []byte {
	if m != nil {
		return m.ContractName
	}
	return nil
}

type Transaction_Result struct {
	Fee int64                  `protobuf:"varint,1,opt,name=fee" json:"fee,omitempty"`
	Ret Transaction_ResultCode `protobuf:"varint,2,opt,name=ret,enum=protocol.Transaction_ResultCode" json:"ret,omitempty"`
}

func (m *Transaction_Result) Reset()                    { *m = Transaction_Result{} }
func (m *Transaction_Result) String() string            { return proto.CompactTextString(m) }
func (*Transaction_Result) ProtoMessage()               {}
func (*Transaction_Result) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8, 1} }

func (m *Transaction_Result) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Transaction_Result) GetRet() Transaction_ResultCode {
	if m != nil {
		return m.Ret
	}
	return Transaction_Result_SUCESS
}

type TransactionRaw struct {
	Type         Transaction_TransactionType `protobuf:"varint,1,opt,name=type,enum=protocol.Transaction_TransactionType" json:"type,omitempty"`
	RefBlockNum  int64                       `protobuf:"varint,3,opt,name=ref_block_num,json=refBlockNum" json:"ref_block_num,omitempty"`
	RefBlockHash []byte                      `protobuf:"bytes,4,opt,name=ref_block_hash,json=refBlockHash,proto3" json:"ref_block_hash,omitempty"`
	Expiration   int64                       `protobuf:"varint,8,opt,name=expiration" json:"expiration,omitempty"`
	Auths        []*Acuthrity                `protobuf:"bytes,9,rep,name=auths" json:"auths,omitempty"`
	// data not used
	Data     []byte                  `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	Contract []*Transaction_Contract `protobuf:"bytes,11,rep,name=contract" json:"contract,omitempty"`
	// scripts not used
	Scripts   []byte `protobuf:"bytes,12,opt,name=scripts,proto3" json:"scripts,omitempty"`
	Timestamp int64  `protobuf:"varint,14,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *TransactionRaw) Reset()                    { *m = TransactionRaw{} }
func (m *TransactionRaw) String() string            { return proto.CompactTextString(m) }
func (*TransactionRaw) ProtoMessage()               {}
func (*TransactionRaw) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8, 2} }

func (m *TransactionRaw) GetType() Transaction_TransactionType {
	if m != nil {
		return m.Type
	}
	return Transaction_UtxoType
}

func (m *TransactionRaw) GetRefBlockNum() int64 {
	if m != nil {
		return m.RefBlockNum
	}
	return 0
}

func (m *TransactionRaw) GetRefBlockHash() []byte {
	if m != nil {
		return m.RefBlockHash
	}
	return nil
}

func (m *TransactionRaw) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *TransactionRaw) GetAuths() []*Acuthrity {
	if m != nil {
		return m.Auths
	}
	return nil
}

func (m *TransactionRaw) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TransactionRaw) GetContract() []*Transaction_Contract {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *TransactionRaw) GetScripts() []byte {
	if m != nil {
		return m.Scripts
	}
	return nil
}

func (m *TransactionRaw) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BlockHeader struct {
	RawData          *BlockHeaderRaw `protobuf:"bytes,1,opt,name=raw_data,json=rawData" json:"raw_data,omitempty"`
	WitnessSignature []byte          `protobuf:"bytes,2,opt,name=witness_signature,json=witnessSignature,proto3" json:"witness_signature,omitempty"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *BlockHeader) GetRawData() *BlockHeaderRaw {
	if m != nil {
		return m.RawData
	}
	return nil
}

func (m *BlockHeader) GetWitnessSignature() []byte {
	if m != nil {
		return m.WitnessSignature
	}
	return nil
}

type BlockHeaderRaw struct {
	Timestamp  int64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	TxTrieRoot []byte `protobuf:"bytes,2,opt,name=txTrieRoot,proto3" json:"txTrieRoot,omitempty"`
	ParentHash []byte `protobuf:"bytes,3,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	// bytes nonce = 5;
	// bytes difficulty = 6;
	Number         int64  `protobuf:"varint,7,opt,name=number" json:"number,omitempty"`
	WitnessId      int64  `protobuf:"varint,8,opt,name=witness_id,json=witnessId" json:"witness_id,omitempty"`
	WitnessAddress []byte `protobuf:"bytes,9,opt,name=witness_address,json=witnessAddress,proto3" json:"witness_address,omitempty"`
}

func (m *BlockHeaderRaw) Reset()                    { *m = BlockHeaderRaw{} }
func (m *BlockHeaderRaw) String() string            { return proto.CompactTextString(m) }
func (*BlockHeaderRaw) ProtoMessage()               {}
func (*BlockHeaderRaw) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9, 0} }

func (m *BlockHeaderRaw) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeaderRaw) GetTxTrieRoot() []byte {
	if m != nil {
		return m.TxTrieRoot
	}
	return nil
}

func (m *BlockHeaderRaw) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeaderRaw) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BlockHeaderRaw) GetWitnessId() int64 {
	if m != nil {
		return m.WitnessId
	}
	return 0
}

func (m *BlockHeaderRaw) GetWitnessAddress() []byte {
	if m != nil {
		return m.WitnessAddress
	}
	return nil
}

// block
type Block struct {
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
	BlockHeader  *BlockHeader   `protobuf:"bytes,2,opt,name=block_header,json=blockHeader" json:"block_header,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetBlockHeader() *BlockHeader {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

type ChainInventory struct {
	Ids       []*ChainInventory_BlockId `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	RemainNum int64                     `protobuf:"varint,2,opt,name=remain_num,json=remainNum" json:"remain_num,omitempty"`
}

func (m *ChainInventory) Reset()                    { *m = ChainInventory{} }
func (m *ChainInventory) String() string            { return proto.CompactTextString(m) }
func (*ChainInventory) ProtoMessage()               {}
func (*ChainInventory) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *ChainInventory) GetIds() []*ChainInventory_BlockId {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ChainInventory) GetRemainNum() int64 {
	if m != nil {
		return m.RemainNum
	}
	return 0
}

type ChainInventory_BlockId struct {
	Hash   []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Number int64  `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
}

func (m *ChainInventory_BlockId) Reset()                    { *m = ChainInventory_BlockId{} }
func (m *ChainInventory_BlockId) String() string            { return proto.CompactTextString(m) }
func (*ChainInventory_BlockId) ProtoMessage()               {}
func (*ChainInventory_BlockId) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11, 0} }

func (m *ChainInventory_BlockId) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ChainInventory_BlockId) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

// Inventory
type BlockInventory struct {
	Ids  []*BlockInventory_BlockId `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	Type BlockInventory_Type       `protobuf:"varint,2,opt,name=type,enum=protocol.BlockInventory_Type" json:"type,omitempty"`
}

func (m *BlockInventory) Reset()                    { *m = BlockInventory{} }
func (m *BlockInventory) String() string            { return proto.CompactTextString(m) }
func (*BlockInventory) ProtoMessage()               {}
func (*BlockInventory) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *BlockInventory) GetIds() []*BlockInventory_BlockId {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *BlockInventory) GetType() BlockInventory_Type {
	if m != nil {
		return m.Type
	}
	return BlockInventory_SYNC
}

type BlockInventory_BlockId struct {
	Hash   []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Number int64  `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
}

func (m *BlockInventory_BlockId) Reset()                    { *m = BlockInventory_BlockId{} }
func (m *BlockInventory_BlockId) String() string            { return proto.CompactTextString(m) }
func (*BlockInventory_BlockId) ProtoMessage()               {}
func (*BlockInventory_BlockId) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12, 0} }

func (m *BlockInventory_BlockId) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockInventory_BlockId) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type Inventory struct {
	Type Inventory_InventoryType `protobuf:"varint,1,opt,name=type,enum=protocol.Inventory_InventoryType" json:"type,omitempty"`
	Ids  [][]byte                `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (m *Inventory) Reset()                    { *m = Inventory{} }
func (m *Inventory) String() string            { return proto.CompactTextString(m) }
func (*Inventory) ProtoMessage()               {}
func (*Inventory) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *Inventory) GetType() Inventory_InventoryType {
	if m != nil {
		return m.Type
	}
	return Inventory_TRX
}

func (m *Inventory) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Items struct {
	Type         Items_ItemType `protobuf:"varint,1,opt,name=type,enum=protocol.Items_ItemType" json:"type,omitempty"`
	Blocks       []*Block       `protobuf:"bytes,2,rep,name=blocks" json:"blocks,omitempty"`
	BlockHeaders []*BlockHeader `protobuf:"bytes,3,rep,name=block_headers,json=blockHeaders" json:"block_headers,omitempty"`
	Transactions []*Transaction `protobuf:"bytes,4,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *Items) Reset()                    { *m = Items{} }
func (m *Items) String() string            { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()               {}
func (*Items) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *Items) GetType() Items_ItemType {
	if m != nil {
		return m.Type
	}
	return Items_ERR
}

func (m *Items) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *Items) GetBlockHeaders() []*BlockHeader {
	if m != nil {
		return m.BlockHeaders
	}
	return nil
}

func (m *Items) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

// DynamicProperties
type DynamicProperties struct {
	LastSolidityBlockNum int64 `protobuf:"varint,1,opt,name=last_solidity_block_num,json=lastSolidityBlockNum" json:"last_solidity_block_num,omitempty"`
}

func (m *DynamicProperties) Reset()                    { *m = DynamicProperties{} }
func (m *DynamicProperties) String() string            { return proto.CompactTextString(m) }
func (*DynamicProperties) ProtoMessage()               {}
func (*DynamicProperties) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func (m *DynamicProperties) GetLastSolidityBlockNum() int64 {
	if m != nil {
		return m.LastSolidityBlockNum
	}
	return 0
}

type DisconnectMessage struct {
	Reason ReasonCode `protobuf:"varint,1,opt,name=reason,enum=protocol.ReasonCode" json:"reason,omitempty"`
}

func (m *DisconnectMessage) Reset()                    { *m = DisconnectMessage{} }
func (m *DisconnectMessage) String() string            { return proto.CompactTextString(m) }
func (*DisconnectMessage) ProtoMessage()               {}
func (*DisconnectMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

func (m *DisconnectMessage) GetReason() ReasonCode {
	if m != nil {
		return m.Reason
	}
	return ReasonCode_REQUESTED
}

type HelloMessage struct {
	From      *Endpoint `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Version   int32     `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Timestamp int64     `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *HelloMessage) Reset()                    { *m = HelloMessage{} }
func (m *HelloMessage) String() string            { return proto.CompactTextString(m) }
func (*HelloMessage) ProtoMessage()               {}
func (*HelloMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{17} }

func (m *HelloMessage) GetFrom() *Endpoint {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *HelloMessage) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *HelloMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*AccountId)(nil), "protocol.AccountId")
	proto.RegisterType((*Account)(nil), "protocol.Account")
	proto.RegisterType((*Account_Vote)(nil), "protocol.Account.Vote")
	proto.RegisterType((*Account_Frozen)(nil), "protocol.Account.Frozen")
	proto.RegisterType((*Acuthrity)(nil), "protocol.acuthrity")
	proto.RegisterType((*Permision)(nil), "protocol.permision")
	proto.RegisterType((*Witness)(nil), "protocol.Witness")
	proto.RegisterType((*TXOutput)(nil), "protocol.TXOutput")
	proto.RegisterType((*TXInput)(nil), "protocol.TXInput")
	proto.RegisterType((*TXInputRaw)(nil), "protocol.TXInput.raw")
	proto.RegisterType((*TXOutputs)(nil), "protocol.TXOutputs")
	proto.RegisterType((*Transaction)(nil), "protocol.Transaction")
	proto.RegisterType((*Transaction_Contract)(nil), "protocol.Transaction.Contract")
	proto.RegisterType((*Transaction_Result)(nil), "protocol.Transaction.Result")
	proto.RegisterType((*TransactionRaw)(nil), "protocol.Transaction.raw")
	proto.RegisterType((*BlockHeader)(nil), "protocol.BlockHeader")
	proto.RegisterType((*BlockHeaderRaw)(nil), "protocol.BlockHeader.raw")
	proto.RegisterType((*Block)(nil), "protocol.Block")
	proto.RegisterType((*ChainInventory)(nil), "protocol.ChainInventory")
	proto.RegisterType((*ChainInventory_BlockId)(nil), "protocol.ChainInventory.BlockId")
	proto.RegisterType((*BlockInventory)(nil), "protocol.BlockInventory")
	proto.RegisterType((*BlockInventory_BlockId)(nil), "protocol.BlockInventory.BlockId")
	proto.RegisterType((*Inventory)(nil), "protocol.Inventory")
	proto.RegisterType((*Items)(nil), "protocol.Items")
	proto.RegisterType((*DynamicProperties)(nil), "protocol.DynamicProperties")
	proto.RegisterType((*DisconnectMessage)(nil), "protocol.DisconnectMessage")
	proto.RegisterType((*HelloMessage)(nil), "protocol.HelloMessage")
	proto.RegisterEnum("protocol.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("protocol.ReasonCode", ReasonCode_name, ReasonCode_value)
	proto.RegisterEnum("protocol.Transaction_TransactionType", Transaction_TransactionType_name, Transaction_TransactionType_value)
	proto.RegisterEnum("protocol.Transaction_Contract_ContractType", Transaction_Contract_ContractType_name, Transaction_Contract_ContractType_value)
	proto.RegisterEnum("protocol.Transaction_ResultCode", Transaction_ResultCode_name, Transaction_ResultCode_value)
	proto.RegisterEnum("protocol.BlockInventory_Type", BlockInventory_Type_name, BlockInventory_Type_value)
	proto.RegisterEnum("protocol.Inventory_InventoryType", Inventory_InventoryType_name, Inventory_InventoryType_value)
	proto.RegisterEnum("protocol.Items_ItemType", Items_ItemType_name, Items_ItemType_value)
}

func init() { proto.RegisterFile("core/Tron.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 2134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xcb, 0x76, 0xdb, 0xc6,
	0x19, 0x16, 0xef, 0xe4, 0x4f, 0x4a, 0x82, 0xc6, 0x92, 0x4d, 0xab, 0x4e, 0xa2, 0xa0, 0x4d, 0x62,
	0xe7, 0x42, 0x39, 0x4a, 0x7d, 0x6a, 0x7b, 0xd3, 0x52, 0x24, 0x1c, 0x21, 0x96, 0x49, 0x06, 0x04,
	0x7d, 0xe9, 0x86, 0x67, 0x04, 0x8e, 0x24, 0x9c, 0x90, 0x00, 0xcf, 0x60, 0x28, 0x99, 0x39, 0x7d,
	0x87, 0x2e, 0xba, 0x6a, 0x57, 0xdd, 0xf4, 0x15, 0xfa, 0x02, 0xdd, 0x75, 0xdf, 0x73, 0xba, 0xe9,
	0x23, 0xf4, 0x19, 0xda, 0xf3, 0xcf, 0x0c, 0x08, 0x40, 0x92, 0xdd, 0xcb, 0x46, 0x9a, 0xf9, 0xfe,
	0xcb, 0xcc, 0xfc, 0x77, 0x10, 0x36, 0xbd, 0x90, 0xb3, 0x7d, 0x97, 0x87, 0x41, 0x6b, 0xce, 0x43,
	0x11, 0x92, 0xaa, 0xfc, 0xe7, 0x85, 0xd3, 0xdd, 0xbb, 0x67, 0x61, 0x78, 0x36, 0x65, 0xfb, 0x12,
	0x38, 0x59, 0x9c, 0xee, 0xd3, 0x60, 0xa9, 0x98, 0x76, 0x6f, 0x49, 0xa9, 0xae, 0x1f, 0x79, 0xe1,
	0x05, 0xe3, 0x0a, 0x34, 0x9f, 0x40, 0xad, 0xed, 0x79, 0xe1, 0x22, 0x10, 0xf6, 0x84, 0x10, 0x28,
	0x06, 0x74, 0xc6, 0x9a, 0xb9, 0xbd, 0xdc, 0xfd, 0x86, 0x23, 0xd7, 0xa4, 0x09, 0x15, 0x3a, 0x99,
	0x70, 0x16, 0x45, 0xcd, 0xbc, 0x84, 0xe3, 0xad, 0xf9, 0xd7, 0x12, 0x54, 0xb4, 0x2c, 0xf9, 0x18,
	0x1a, 0x54, 0x2d, 0xc7, 0x29, 0x0d, 0x75, 0x8d, 0xf5, 0x50, 0xd1, 0x03, 0x28, 0x8a, 0xe5, 0x9c,
	0x49, 0x2d, 0x1b, 0x07, 0x3b, 0xad, 0xf8, 0xca, 0x2d, 0xad, 0xc3, 0x5d, 0xce, 0x99, 0x23, 0x59,
	0xd2, 0x67, 0x16, 0x32, 0x67, 0x22, 0xe5, 0x84, 0x4e, 0x69, 0xe0, 0xb1, 0x66, 0x71, 0x2f, 0x77,
	0xbf, 0xe0, 0xc4, 0x5b, 0xf2, 0x25, 0x94, 0x2e, 0x42, 0xc1, 0xa2, 0x66, 0x69, 0xaf, 0x70, 0xbf,
	0x7e, 0x70, 0xfb, 0x9a, 0xfe, 0xd6, 0xcb, 0x50, 0x30, 0x47, 0x31, 0x91, 0x03, 0x28, 0xd1, 0x28,
	0x62, 0xa2, 0x59, 0x96, 0xdc, 0xf7, 0xae, 0x73, 0xb7, 0x91, 0x6c, 0x05, 0x82, 0x2f, 0x1d, 0xc5,
	0x4a, 0x1e, 0x42, 0xf9, 0x94, 0x87, 0x3f, 0xb2, 0xa0, 0x59, 0x91, 0x42, 0xcd, 0xeb, 0x42, 0xcf,
	0x24, 0xdd, 0xd1, 0x7c, 0xe4, 0x1e, 0xd4, 0x4e, 0x68, 0x30, 0xb9, 0xf4, 0x27, 0xe2, 0xbc, 0x59,
	0x95, 0xf7, 0x4d, 0x00, 0xf2, 0x11, 0xd4, 0x3d, 0xce, 0xa8, 0x60, 0x63, 0xe1, 0xcf, 0x58, 0xb3,
	0x26, 0xe9, 0xa0, 0x20, 0xd7, 0x9f, 0x31, 0xf2, 0x10, 0xb6, 0xa7, 0x54, 0xb0, 0x48, 0x8c, 0xc3,
	0x39, 0xa7, 0xc2, 0x0f, 0x03, 0xc5, 0x09, 0x92, 0x93, 0x28, 0x5a, 0x5f, 0x93, 0xa4, 0xc4, 0x3d,
	0xa8, 0xd1, 0xe9, 0x34, 0xbc, 0x94, 0x06, 0xaa, 0xab, 0x03, 0x57, 0x40, 0x4a, 0xdf, 0xa5, 0x2f,
	0xce, 0x27, 0x9c, 0x5e, 0x2a, 0x7d, 0x8d, 0xb4, 0xbe, 0x57, 0x9a, 0x24, 0xf5, 0x11, 0x28, 0x7a,
	0xe1, 0x84, 0x35, 0xd7, 0x55, 0x40, 0xe0, 0x7a, 0xf7, 0x08, 0x8a, 0x68, 0x49, 0x74, 0x39, 0xda,
	0x72, 0x1c, 0x7b, 0x4a, 0xbb, 0x1c, 0xb1, 0xb6, 0xf6, 0xd6, 0x07, 0x00, 0x92, 0x45, 0x1a, 0x47,
	0x3a, 0xbe, 0xe0, 0xd4, 0x10, 0xe9, 0x20, 0xb0, 0x3b, 0x80, 0xb2, 0x32, 0x18, 0xf9, 0x04, 0x36,
	0x94, 0xc9, 0xc6, 0xb1, 0x77, 0x73, 0x92, 0x79, 0x5d, 0xa1, 0x87, 0xda, 0xc7, 0x1f, 0x41, 0x9d,
	0xbd, 0x9d, 0xfb, 0x5c, 0x5b, 0x4c, 0x29, 0x04, 0x05, 0xe1, 0x7d, 0x77, 0x1f, 0x03, 0x24, 0x7e,
	0x23, 0x06, 0x14, 0x7e, 0x60, 0x4b, 0xa9, 0xaa, 0xe6, 0xe0, 0x92, 0x6c, 0x43, 0xe9, 0x82, 0x4e,
	0x17, 0xb1, 0xa8, 0xda, 0x3c, 0xcd, 0x3f, 0xce, 0x99, 0x1e, 0xd4, 0xa8, 0xb7, 0x10, 0xe7, 0xdc,
	0x17, 0x4b, 0xf2, 0x15, 0x54, 0x74, 0xe4, 0x4a, 0xe1, 0xfa, 0xc1, 0xad, 0x6b, 0xae, 0xb6, 0x27,
	0x4e, 0xcc, 0x43, 0x3e, 0x83, 0xcd, 0x39, 0xe3, 0x33, 0x3f, 0x8a, 0xd0, 0x45, 0x32, 0xfe, 0x55,
	0xaa, 0x6c, 0x24, 0x30, 0xa6, 0x80, 0xf9, 0x14, 0x6a, 0x0a, 0xf1, 0xc3, 0xe0, 0x7f, 0x3c, 0xc4,
	0xfc, 0x7d, 0x1e, 0x2a, 0xaf, 0x7c, 0x11, 0xe8, 0x2c, 0xc8, 0x5a, 0x7d, 0x95, 0x1f, 0xf7, 0x20,
	0xb1, 0xef, 0x35, 0x83, 0x93, 0xdb, 0x50, 0x9e, 0x2f, 0x4e, 0x9e, 0xb3, 0xa5, 0x4e, 0x2b, 0xbd,
	0x43, 0x43, 0x2d, 0xf8, 0x54, 0x66, 0x54, 0xcd, 0xc1, 0x25, 0xf9, 0x19, 0xac, 0x8b, 0x50, 0xd0,
	0xe9, 0x80, 0x87, 0x93, 0x85, 0xc7, 0x26, 0xcd, 0x92, 0xf2, 0x47, 0x06, 0x24, 0x7b, 0x50, 0x97,
	0xc0, 0x0b, 0x3f, 0x8a, 0xd8, 0xa4, 0x59, 0x96, 0x3c, 0x69, 0x88, 0x7c, 0x0a, 0x1b, 0x2a, 0xac,
	0x0e, 0xa7, 0xa1, 0xf7, 0x43, 0x6f, 0x31, 0x6b, 0x56, 0x24, 0xd3, 0x15, 0x14, 0xcf, 0x53, 0xc8,
	0x70, 0x1a, 0x0a, 0x64, 0x53, 0xd9, 0x92, 0x05, 0xf1, 0xfe, 0x7e, 0xf4, 0x5d, 0x78, 0x12, 0xc9,
	0x64, 0xa9, 0x3a, 0x7a, 0x67, 0xfe, 0x0a, 0xaa, 0xee, 0xeb, 0xfe, 0x42, 0xcc, 0x17, 0x22, 0x71,
	0x71, 0x2e, 0xe5, 0x62, 0xf2, 0x21, 0x80, 0x7a, 0xeb, 0x11, 0x8d, 0xce, 0xb5, 0x77, 0x52, 0x88,
	0xf9, 0xc7, 0x1c, 0x54, 0xdc, 0xd7, 0x76, 0x80, 0x1a, 0x1e, 0x42, 0x15, 0x53, 0x63, 0x42, 0x05,
	0xd5, 0x9e, 0x49, 0x15, 0x2b, 0xcd, 0xd4, 0xe2, 0xf4, 0xd2, 0xa9, 0x70, 0x7a, 0xd9, 0xa5, 0x82,
	0xa2, 0xd5, 0x23, 0xff, 0x2c, 0xa0, 0x62, 0xc1, 0x55, 0x5d, 0x6a, 0x38, 0x09, 0xb0, 0x6b, 0x41,
	0x81, 0xd3, 0x4b, 0xcc, 0x25, 0xf1, 0xd6, 0xee, 0xc6, 0xc5, 0x15, 0xd7, 0x88, 0x5d, 0x84, 0x8b,
	0xd8, 0x53, 0x72, 0xfd, 0x2e, 0x27, 0x61, 0xa5, 0x8e, 0x1f, 0x19, 0x91, 0x2f, 0xa1, 0x12, 0xaa,
	0x65, 0x33, 0x27, 0x8b, 0x11, 0x49, 0x5f, 0x51, 0x71, 0x39, 0x31, 0x8b, 0xf9, 0xcf, 0x1a, 0xd4,
	0x5d, 0x4e, 0x83, 0x88, 0x7a, 0x58, 0x2a, 0xc8, 0xcf, 0xaf, 0xbd, 0xf0, 0x6e, 0x4a, 0x3c, 0x61,
	0x7c, 0xcf, 0x2b, 0xf3, 0x7b, 0x85, 0xcc, 0x2b, 0x49, 0x0b, 0x0a, 0x9c, 0x09, 0x5d, 0x7d, 0xef,
	0xdd, 0xac, 0xce, 0x61, 0xd1, 0x62, 0x2a, 0x1c, 0x64, 0xdc, 0xfd, 0x5b, 0x11, 0xaa, 0x9d, 0x30,
	0x10, 0x9c, 0x7a, 0x82, 0xfc, 0x52, 0xf7, 0x86, 0x9c, 0xec, 0x0d, 0x5f, 0xdc, 0x2c, 0x1d, 0x73,
	0xaf, 0x16, 0xa9, 0x8e, 0x71, 0x00, 0xb5, 0x39, 0xe5, 0x74, 0xc6, 0x04, 0xe3, 0xd2, 0x9a, 0xf5,
	0x83, 0xed, 0x96, 0x6a, 0x85, 0xad, 0xb8, 0x15, 0xb6, 0xda, 0xc1, 0xd2, 0x49, 0xd8, 0xc8, 0x2e,
	0x60, 0xdb, 0xbc, 0xf0, 0x27, 0x8c, 0x6b, 0x53, 0xaf, 0xf6, 0xc4, 0x84, 0x46, 0x7c, 0x0a, 0x66,
	0xae, 0x76, 0x6a, 0x06, 0x33, 0x7f, 0x57, 0x48, 0x98, 0xf0, 0x2a, 0xe4, 0x2e, 0xec, 0xe8, 0xc4,
	0xed, 0xc8, 0x22, 0x1e, 0x13, 0x8d, 0x35, 0xb2, 0x0d, 0x86, 0x7c, 0xca, 0x29, 0xe3, 0x2b, 0x34,
	0x87, 0x02, 0x31, 0x2a, 0xcb, 0xd6, 0x8a, 0x94, 0x27, 0x3b, 0xb0, 0x85, 0x55, 0x36, 0x0b, 0x17,
	0xc8, 0x1d, 0xb8, 0x85, 0xb0, 0x2e, 0x04, 0x2b, 0x42, 0x11, 0x55, 0xc5, 0x60, 0xf6, 0xec, 0x12,
	0xb9, 0x0d, 0x44, 0xaa, 0xb1, 0xa3, 0x68, 0x91, 0xe0, 0x65, 0x42, 0x60, 0xa3, 0xcb, 0xe6, 0xd3,
	0x70, 0xb9, 0xc2, 0x2a, 0x29, 0x35, 0xa3, 0xf9, 0x24, 0xad, 0xa6, 0x4a, 0x3e, 0x86, 0x0f, 0x06,
	0x94, 0x0b, 0xdf, 0xf3, 0xe7, 0x54, 0x5f, 0x2c, 0xab, 0xb1, 0x96, 0x32, 0xc0, 0x15, 0x69, 0x40,
	0xd2, 0x33, 0xce, 0xd8, 0x8f, 0x4c, 0xd7, 0xf2, 0x15, 0xa9, 0x4e, 0x7e, 0x02, 0x77, 0x46, 0xc1,
	0xe9, 0x8d, 0xc4, 0x06, 0x12, 0xe3, 0x8e, 0x74, 0x95, 0xb8, 0x8e, 0x2f, 0xe8, 0x2c, 0x22, 0x11,
	0xce, 0x56, 0xd8, 0xf6, 0x6e, 0x08, 0x65, 0x15, 0x66, 0x58, 0xd5, 0x4e, 0x59, 0x5c, 0x07, 0x70,
	0x49, 0xbe, 0x51, 0x31, 0xaa, 0x26, 0x90, 0x8f, 0xdf, 0x17, 0xa3, 0x2d, 0x6c, 0x75, 0x32, 0x50,
	0xcd, 0x0f, 0x55, 0x0f, 0x24, 0x00, 0xe5, 0xe1, 0xa8, 0x63, 0x0d, 0x87, 0xc6, 0x1a, 0xae, 0x9f,
	0xb5, 0xed, 0x63, 0xab, 0x6b, 0xe4, 0x76, 0xff, 0x91, 0x57, 0xf9, 0xfd, 0x24, 0x13, 0xc3, 0x9f,
	0xdc, 0xac, 0x3d, 0xb5, 0x4e, 0x45, 0xaf, 0x09, 0xeb, 0x9c, 0x9d, 0x8e, 0x4f, 0xb0, 0x1a, 0x8e,
	0x83, 0xc5, 0x4c, 0x86, 0x63, 0xc1, 0xa9, 0x73, 0x76, 0x9a, 0xaa, 0x90, 0x1b, 0x09, 0xcf, 0x39,
	0x56, 0x31, 0x1d, 0x93, 0x31, 0x13, 0xd6, 0x31, 0xac, 0x73, 0xb2, 0x1d, 0xca, 0x91, 0x40, 0x17,
	0xd1, 0x14, 0x42, 0x1e, 0x40, 0x89, 0x2e, 0xc4, 0x39, 0x16, 0xd0, 0x42, 0xb6, 0xe5, 0xac, 0xba,
	0x9f, 0xa3, 0x38, 0xb0, 0x36, 0xc9, 0x02, 0x01, 0xaa, 0x5e, 0xe1, 0x9a, 0x3c, 0x85, 0xaa, 0xa7,
	0x4d, 0xdd, 0xac, 0x4b, 0x0d, 0x1f, 0xbe, 0x3f, 0x57, 0x9d, 0x15, 0x3f, 0x36, 0xad, 0xc8, 0xe3,
	0xfe, 0x5c, 0x44, 0x72, 0xe0, 0x68, 0x38, 0xf1, 0x16, 0x0b, 0x0b, 0xf6, 0xf3, 0x48, 0xd0, 0xd9,
	0xbc, 0xb9, 0xa1, 0x9a, 0xd6, 0x0a, 0x30, 0xbf, 0x86, 0xcd, 0x2b, 0x56, 0x23, 0x0d, 0xa8, 0x8e,
	0xc4, 0xdb, 0x10, 0xd7, 0xc6, 0x1a, 0x31, 0xb2, 0x69, 0x68, 0xe4, 0xcc, 0x3f, 0xe7, 0xa1, 0xae,
	0x6c, 0xc2, 0x28, 0x66, 0xf3, 0x7b, 0xeb, 0x5d, 0x8a, 0x31, 0x5b, 0xef, 0xbe, 0x80, 0xad, 0x4b,
	0x95, 0x0b, 0xe3, 0x74, 0xdd, 0xc3, 0xab, 0x1b, 0x9a, 0x30, 0x5c, 0x15, 0xf9, 0xbf, 0xe4, 0x54,
	0x14, 0x64, 0xde, 0x92, 0xbb, 0xf2, 0x16, 0x74, 0x8f, 0x78, 0xeb, 0x72, 0x9f, 0x39, 0x61, 0x28,
	0xe2, 0x36, 0x94, 0x20, 0xb2, 0x4d, 0x51, 0xce, 0x02, 0x21, 0xdb, 0x54, 0x41, 0xb7, 0xa9, 0x15,
	0x82, 0xbd, 0x21, 0x58, 0xcc, 0x4e, 0x18, 0xd7, 0x6d, 0x54, 0xef, 0x70, 0xd0, 0x8a, 0xaf, 0xea,
	0x4f, 0xe2, 0x49, 0x53, 0x23, 0xf6, 0x04, 0x07, 0x94, 0x98, 0x1c, 0xcf, 0x0d, 0x35, 0x35, 0xa0,
	0x68, 0x58, 0x0f, 0x6c, 0xe6, 0x6f, 0xa0, 0x24, 0xcd, 0x41, 0x9e, 0x40, 0x43, 0x24, 0x46, 0x8f,
	0x9b, 0xcc, 0xce, 0x8d, 0xce, 0x76, 0x32, 0xac, 0xe4, 0x31, 0x34, 0x74, 0x90, 0x4a, 0x9b, 0xea,
	0x6a, 0xbc, 0x73, 0xa3, 0xc1, 0x9d, 0xfa, 0x49, 0xb2, 0x31, 0xff, 0x90, 0x83, 0x8d, 0xce, 0x39,
	0xf5, 0x03, 0x3b, 0xb8, 0x60, 0x81, 0x08, 0xf9, 0x92, 0x1c, 0x40, 0xc1, 0x9f, 0xc4, 0xc7, 0xef,
	0x25, 0x3a, 0xb2, 0x6c, 0x4a, 0xa5, 0x3d, 0x71, 0x90, 0x19, 0x8d, 0xc1, 0xd9, 0x8c, 0xfa, 0x81,
	0x4c, 0x25, 0x3d, 0x04, 0x29, 0xa4, 0xb7, 0x98, 0xed, 0x3e, 0x82, 0x8a, 0x66, 0xc7, 0x10, 0x97,
	0x99, 0xa4, 0x5b, 0xf2, 0x79, 0xd6, 0xc4, 0xf9, 0xb4, 0x89, 0xcd, 0xbf, 0xe7, 0x60, 0x43, 0xc9,
	0xfd, 0xc7, 0xcb, 0x65, 0xd9, 0xb2, 0x97, 0xfb, 0x3a, 0xf3, 0x15, 0xf4, 0xc1, 0x3b, 0x85, 0x92,
	0xea, 0xf0, 0xff, 0x5e, 0xf8, 0x3e, 0x14, 0x65, 0xb2, 0x54, 0xa1, 0x38, 0x7c, 0xd3, 0xeb, 0x18,
	0x6b, 0xa4, 0x0e, 0x95, 0x76, 0xf7, 0xa5, 0x6b, 0x0f, 0x2d, 0x23, 0x47, 0x6a, 0x50, 0x7a, 0x66,
	0xb9, 0x9d, 0x23, 0x23, 0x6f, 0x2e, 0xa1, 0x96, 0x3c, 0xea, 0x51, 0xa6, 0x8c, 0xa5, 0x8a, 0x64,
	0x72, 0xb7, 0xd5, 0x2a, 0x55, 0xc2, 0x0c, 0x65, 0x0b, 0x35, 0x16, 0xe0, 0xd2, 0xfc, 0x29, 0xac,
	0x67, 0x18, 0x49, 0x05, 0x0a, 0xae, 0xf3, 0xda, 0x58, 0xc3, 0xa3, 0x0f, 0x8f, 0xfb, 0x9d, 0xe7,
	0x46, 0xce, 0xfc, 0x6d, 0x1e, 0x4a, 0xb6, 0x60, 0x33, 0x9c, 0x68, 0xd2, 0xe7, 0xa6, 0xbe, 0xad,
	0x24, 0x59, 0xfe, 0x4d, 0x1d, 0xf7, 0x19, 0x94, 0x65, 0xe4, 0xa8, 0x13, 0xeb, 0x07, 0x9b, 0x57,
	0x0c, 0xe9, 0x68, 0x32, 0x79, 0x0a, 0xeb, 0xe9, 0x68, 0xc4, 0x0f, 0xca, 0xc2, 0xbb, 0xc3, 0xb1,
	0x91, 0x0a, 0xc7, 0xe8, 0x5a, 0x12, 0x14, 0xff, 0xeb, 0x24, 0x30, 0x1f, 0x43, 0x35, 0xbe, 0x31,
	0xbe, 0xdb, 0x72, 0x1c, 0x63, 0x2d, 0x36, 0x40, 0x2e, 0x31, 0x40, 0x9e, 0x6c, 0x42, 0x5d, 0x2e,
	0x8f, 0xac, 0x76, 0xd7, 0x72, 0x8c, 0x82, 0xf9, 0x1d, 0x6c, 0x75, 0x97, 0x01, 0x9d, 0xf9, 0xde,
	0x80, 0x87, 0x73, 0xc6, 0x85, 0xcf, 0x22, 0xf2, 0x08, 0xee, 0x4c, 0x69, 0x24, 0xc6, 0x51, 0x38,
	0xf5, 0x27, 0xbe, 0x58, 0xa6, 0x5a, 0x85, 0xaa, 0x31, 0xdb, 0x48, 0x1e, 0x6a, 0x6a, 0xdc, 0x33,
	0xcc, 0x36, 0x6c, 0xc9, 0xcf, 0xfd, 0x20, 0x60, 0x9e, 0x78, 0xc1, 0xa2, 0x88, 0x9e, 0xe1, 0x87,
	0x72, 0x99, 0x33, 0x1a, 0x85, 0x81, 0x36, 0xf5, 0x76, 0xf2, 0x1e, 0x47, 0xe2, 0x1d, 0x6c, 0x7d,
	0x9a, 0xc7, 0x0c, 0xa0, 0x71, 0xc4, 0xa6, 0xd3, 0x30, 0x96, 0xfe, 0x14, 0x8a, 0xa7, 0x3c, 0x9c,
	0xe9, 0x32, 0x9a, 0x9a, 0x3a, 0xad, 0x60, 0x32, 0x0f, 0xfd, 0x40, 0x38, 0x92, 0x8e, 0xd5, 0xfe,
	0x82, 0x71, 0xfc, 0xd0, 0x91, 0x61, 0x59, 0x72, 0xe2, 0x6d, 0xb6, 0x42, 0x16, 0xae, 0x54, 0xc8,
	0xcf, 0x7f, 0x01, 0xf5, 0xd4, 0xef, 0x01, 0xd8, 0x68, 0x7b, 0x21, 0x9f, 0xd1, 0xa9, 0xb1, 0x46,
	0x36, 0xf4, 0xc7, 0x9d, 0x9c, 0x3a, 0x8c, 0x1c, 0x76, 0x81, 0x64, 0x60, 0xfa, 0xfc, 0x4f, 0x05,
	0x80, 0xe4, 0xfe, 0x64, 0x1d, 0x6a, 0x8e, 0xf5, 0xfd, 0xc8, 0x1a, 0xba, 0x56, 0xd7, 0x58, 0xc3,
	0xad, 0xdb, 0x19, 0x8c, 0x2d, 0xc7, 0xe9, 0x3b, 0x46, 0x0e, 0x5b, 0xc6, 0x61, 0xbb, 0x3b, 0x1e,
	0x38, 0x7d, 0xb7, 0xdf, 0xe9, 0x1f, 0x1b, 0x79, 0x44, 0x46, 0x43, 0xeb, 0xd8, 0x1a, 0x0e, 0xc7,
	0x03, 0x0b, 0x1d, 0x81, 0xc3, 0x85, 0xdb, 0xef, 0x8f, 0x5f, 0xb4, 0x7b, 0x6f, 0x24, 0x34, 0x34,
	0x8a, 0x72, 0x64, 0x1a, 0x0d, 0x8e, 0xed, 0x4e, 0xdb, 0xb5, 0x14, 0x5f, 0x09, 0x27, 0x1b, 0xbb,
	0xd7, 0xe9, 0xbf, 0x18, 0xb4, 0x5d, 0xfb, 0xf0, 0xd8, 0x4a, 0x94, 0x96, 0xc9, 0x16, 0xac, 0xf7,
	0x46, 0xc7, 0xc7, 0x63, 0xbb, 0x6b, 0xf5, 0x5c, 0xdb, 0x7d, 0x63, 0x54, 0xf0, 0x1c, 0x94, 0x1b,
	0x7f, 0x3f, 0xb2, 0x5d, 0xbb, 0xf7, 0xad, 0x51, 0xc5, 0x91, 0x6e, 0xd4, 0xb3, 0x5e, 0x0f, 0xac,
	0x8e, 0x6b, 0x75, 0x13, 0xd6, 0x1a, 0x1e, 0x76, 0xdc, 0xef, 0xb4, 0x53, 0xe2, 0x20, 0xc5, 0xed,
	0xde, 0xb7, 0x63, 0xd7, 0x7e, 0x61, 0xf5, 0x47, 0xae, 0x51, 0xc7, 0x00, 0x1a, 0x0d, 0x2d, 0x67,
	0xec, 0x58, 0xed, 0x61, 0xbf, 0x67, 0x18, 0x18, 0x5c, 0x8e, 0x35, 0xb4, 0x5c, 0x63, 0x0b, 0x5f,
	0x8d, 0xa9, 0x3f, 0xc6, 0x59, 0xc5, 0x20, 0x68, 0x30, 0x94, 0x1b, 0xa3, 0xe0, 0x2d, 0x34, 0x2d,
	0xda, 0xc0, 0x7d, 0x6d, 0x6c, 0x23, 0x23, 0xae, 0x55, 0x50, 0xee, 0xc8, 0xf1, 0xa6, 0xef, 0x3c,
	0xb7, 0xba, 0xc6, 0x6d, 0xb4, 0xfa, 0xa8, 0x77, 0x6c, 0xf7, 0x9e, 0xb7, 0x0f, 0x8f, 0x2d, 0xe3,
	0x0e, 0x69, 0xc2, 0x76, 0xe6, 0xb9, 0x2f, 0x2d, 0x67, 0x68, 0xf7, 0x7b, 0x46, 0x13, 0xe7, 0xcc,
	0x0c, 0xa5, 0x73, 0xd4, 0xb6, 0x7b, 0xc6, 0x5d, 0xd2, 0x80, 0xca, 0xa8, 0xf7, 0xbc, 0xd7, 0x7f,
	0xd5, 0x33, 0xfe, 0x95, 0x3b, 0x7c, 0x06, 0x9b, 0x21, 0x3f, 0x6b, 0x89, 0xd5, 0x8f, 0x57, 0xd1,
	0x61, 0x75, 0xa0, 0x83, 0xe8, 0xd7, 0x0f, 0xce, 0x7c, 0x71, 0xbe, 0x38, 0x69, 0x79, 0xe1, 0x6c,
	0x1f, 0x39, 0xe2, 0xe8, 0xda, 0x3f, 0xe3, 0x73, 0xef, 0xab, 0x33, 0x2a, 0xd8, 0x25, 0x5d, 0xee,
	0x7b, 0x21, 0x67, 0x27, 0x65, 0x49, 0xfb, 0xe6, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x02, 0xc4,
	0x72, 0xd9, 0x0c, 0x13, 0x00, 0x00,
}
