// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api/api.proto

It has these top-level messages:
	BlockReference
	Return
	AccountList
	WitnessList
	AssetIssueList
	BlockList
	TransactionList
	NodeList
	Node
	Address
	EmptyMessage
	NumberMessage
	BytesMessage
	TimeMessage
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import protocol1 "github.com/tronprotocol/grpc-gateway/core"
import protocol2 "github.com/tronprotocol/grpc-gateway/core"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockReference struct {
	BlockNum  int64  `protobuf:"varint,1,opt,name=block_num,json=blockNum" json:"block_num,omitempty"`
	BlockHash []byte `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
}

func (m *BlockReference) Reset()                    { *m = BlockReference{} }
func (m *BlockReference) String() string            { return proto.CompactTextString(m) }
func (*BlockReference) ProtoMessage()               {}
func (*BlockReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BlockReference) GetBlockNum() int64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *BlockReference) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type Return struct {
	Result bool `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *Return) Reset()                    { *m = Return{} }
func (m *Return) String() string            { return proto.CompactTextString(m) }
func (*Return) ProtoMessage()               {}
func (*Return) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Return) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type AccountList struct {
	Accounts []*protocol1.Account `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
}

func (m *AccountList) Reset()                    { *m = AccountList{} }
func (m *AccountList) String() string            { return proto.CompactTextString(m) }
func (*AccountList) ProtoMessage()               {}
func (*AccountList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AccountList) GetAccounts() []*protocol1.Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type WitnessList struct {
	Witnesses []*protocol1.Witness `protobuf:"bytes,1,rep,name=witnesses" json:"witnesses,omitempty"`
}

func (m *WitnessList) Reset()                    { *m = WitnessList{} }
func (m *WitnessList) String() string            { return proto.CompactTextString(m) }
func (*WitnessList) ProtoMessage()               {}
func (*WitnessList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WitnessList) GetWitnesses() []*protocol1.Witness {
	if m != nil {
		return m.Witnesses
	}
	return nil
}

type AssetIssueList struct {
	AssetIssue []*protocol2.AssetIssueContract `protobuf:"bytes,1,rep,name=assetIssue" json:"assetIssue,omitempty"`
}

func (m *AssetIssueList) Reset()                    { *m = AssetIssueList{} }
func (m *AssetIssueList) String() string            { return proto.CompactTextString(m) }
func (*AssetIssueList) ProtoMessage()               {}
func (*AssetIssueList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AssetIssueList) GetAssetIssue() []*protocol2.AssetIssueContract {
	if m != nil {
		return m.AssetIssue
	}
	return nil
}

type BlockList struct {
	Block []*protocol1.Block `protobuf:"bytes,1,rep,name=block" json:"block,omitempty"`
}

func (m *BlockList) Reset()                    { *m = BlockList{} }
func (m *BlockList) String() string            { return proto.CompactTextString(m) }
func (*BlockList) ProtoMessage()               {}
func (*BlockList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BlockList) GetBlock() []*protocol1.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type TransactionList struct {
	Transaction []*protocol1.Transaction `protobuf:"bytes,1,rep,name=transaction" json:"transaction,omitempty"`
}

func (m *TransactionList) Reset()                    { *m = TransactionList{} }
func (m *TransactionList) String() string            { return proto.CompactTextString(m) }
func (*TransactionList) ProtoMessage()               {}
func (*TransactionList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TransactionList) GetTransaction() []*protocol1.Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

// Gossip node list
type NodeList struct {
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *NodeList) Reset()                    { *m = NodeList{} }
func (m *NodeList) String() string            { return proto.CompactTextString(m) }
func (*NodeList) ProtoMessage()               {}
func (*NodeList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *NodeList) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// Gossip node
type Node struct {
	Address *Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Node) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

// Gossip node address
type Address struct {
	Host []byte `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Address) GetHost() []byte {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *Address) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type NumberMessage struct {
	Num int64 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
}

func (m *NumberMessage) Reset()                    { *m = NumberMessage{} }
func (m *NumberMessage) String() string            { return proto.CompactTextString(m) }
func (*NumberMessage) ProtoMessage()               {}
func (*NumberMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *NumberMessage) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type BytesMessage struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *BytesMessage) Reset()                    { *m = BytesMessage{} }
func (m *BytesMessage) String() string            { return proto.CompactTextString(m) }
func (*BytesMessage) ProtoMessage()               {}
func (*BytesMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *BytesMessage) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type TimeMessage struct {
	BeginInMilliseconds int64 `protobuf:"varint,1,opt,name=beginInMilliseconds" json:"beginInMilliseconds,omitempty"`
	EndInMilliseconds   int64 `protobuf:"varint,2,opt,name=endInMilliseconds" json:"endInMilliseconds,omitempty"`
}

func (m *TimeMessage) Reset()                    { *m = TimeMessage{} }
func (m *TimeMessage) String() string            { return proto.CompactTextString(m) }
func (*TimeMessage) ProtoMessage()               {}
func (*TimeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *TimeMessage) GetBeginInMilliseconds() int64 {
	if m != nil {
		return m.BeginInMilliseconds
	}
	return 0
}

func (m *TimeMessage) GetEndInMilliseconds() int64 {
	if m != nil {
		return m.EndInMilliseconds
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockReference)(nil), "protocol.BlockReference")
	proto.RegisterType((*Return)(nil), "protocol.Return")
	proto.RegisterType((*AccountList)(nil), "protocol.AccountList")
	proto.RegisterType((*WitnessList)(nil), "protocol.WitnessList")
	proto.RegisterType((*AssetIssueList)(nil), "protocol.AssetIssueList")
	proto.RegisterType((*BlockList)(nil), "protocol.BlockList")
	proto.RegisterType((*TransactionList)(nil), "protocol.TransactionList")
	proto.RegisterType((*NodeList)(nil), "protocol.NodeList")
	proto.RegisterType((*Node)(nil), "protocol.Node")
	proto.RegisterType((*Address)(nil), "protocol.Address")
	proto.RegisterType((*EmptyMessage)(nil), "protocol.EmptyMessage")
	proto.RegisterType((*NumberMessage)(nil), "protocol.NumberMessage")
	proto.RegisterType((*BytesMessage)(nil), "protocol.BytesMessage")
	proto.RegisterType((*TimeMessage)(nil), "protocol.TimeMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Wallet service

type WalletClient interface {
	GetAccount(ctx context.Context, in *protocol1.Account, opts ...grpc.CallOption) (*protocol1.Account, error)
	CreateTransaction(ctx context.Context, in *protocol2.TransferContract, opts ...grpc.CallOption) (*protocol1.Transaction, error)
	BroadcastTransaction(ctx context.Context, in *protocol1.Transaction, opts ...grpc.CallOption) (*Return, error)
	ListAccounts(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*AccountList, error)
	UpdateAccount(ctx context.Context, in *protocol2.AccountUpdateContract, opts ...grpc.CallOption) (*protocol1.Transaction, error)
	CreateAccount(ctx context.Context, in *protocol2.AccountCreateContract, opts ...grpc.CallOption) (*protocol1.Transaction, error)
	VoteWitnessAccount(ctx context.Context, in *protocol2.VoteWitnessContract, opts ...grpc.CallOption) (*protocol1.Transaction, error)
	CreateAssetIssue(ctx context.Context, in *protocol2.AssetIssueContract, opts ...grpc.CallOption) (*protocol1.Transaction, error)
	ListWitnesses(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*WitnessList, error)
	UpdateWitness(ctx context.Context, in *protocol2.WitnessUpdateContract, opts ...grpc.CallOption) (*protocol1.Transaction, error)
	CreateWitness(ctx context.Context, in *protocol2.WitnessCreateContract, opts ...grpc.CallOption) (*protocol1.Transaction, error)
	TransferAsset(ctx context.Context, in *protocol2.TransferAssetContract, opts ...grpc.CallOption) (*protocol1.Transaction, error)
	ParticipateAssetIssue(ctx context.Context, in *protocol2.ParticipateAssetIssueContract, opts ...grpc.CallOption) (*protocol1.Transaction, error)
	ListNodes(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*NodeList, error)
	GetAssetIssueList(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*AssetIssueList, error)
	GetAssetIssueByAccount(ctx context.Context, in *protocol1.Account, opts ...grpc.CallOption) (*AssetIssueList, error)
	GetAssetIssueByName(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*protocol2.AssetIssueContract, error)
	GetNowBlock(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*protocol1.Block, error)
	GetBlockByNum(ctx context.Context, in *NumberMessage, opts ...grpc.CallOption) (*protocol1.Block, error)
	TotalTransaction(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*NumberMessage, error)
}

type walletClient struct {
	cc *grpc.ClientConn
}

func NewWalletClient(cc *grpc.ClientConn) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) GetAccount(ctx context.Context, in *protocol1.Account, opts ...grpc.CallOption) (*protocol1.Account, error) {
	out := new(protocol1.Account)
	err := grpc.Invoke(ctx, "/protocol.Wallet/GetAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) CreateTransaction(ctx context.Context, in *protocol2.TransferContract, opts ...grpc.CallOption) (*protocol1.Transaction, error) {
	out := new(protocol1.Transaction)
	err := grpc.Invoke(ctx, "/protocol.Wallet/CreateTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) BroadcastTransaction(ctx context.Context, in *protocol1.Transaction, opts ...grpc.CallOption) (*Return, error) {
	out := new(Return)
	err := grpc.Invoke(ctx, "/protocol.Wallet/BroadcastTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) ListAccounts(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*AccountList, error) {
	out := new(AccountList)
	err := grpc.Invoke(ctx, "/protocol.Wallet/ListAccounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) UpdateAccount(ctx context.Context, in *protocol2.AccountUpdateContract, opts ...grpc.CallOption) (*protocol1.Transaction, error) {
	out := new(protocol1.Transaction)
	err := grpc.Invoke(ctx, "/protocol.Wallet/UpdateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) CreateAccount(ctx context.Context, in *protocol2.AccountCreateContract, opts ...grpc.CallOption) (*protocol1.Transaction, error) {
	out := new(protocol1.Transaction)
	err := grpc.Invoke(ctx, "/protocol.Wallet/CreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) VoteWitnessAccount(ctx context.Context, in *protocol2.VoteWitnessContract, opts ...grpc.CallOption) (*protocol1.Transaction, error) {
	out := new(protocol1.Transaction)
	err := grpc.Invoke(ctx, "/protocol.Wallet/VoteWitnessAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) CreateAssetIssue(ctx context.Context, in *protocol2.AssetIssueContract, opts ...grpc.CallOption) (*protocol1.Transaction, error) {
	out := new(protocol1.Transaction)
	err := grpc.Invoke(ctx, "/protocol.Wallet/CreateAssetIssue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) ListWitnesses(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*WitnessList, error) {
	out := new(WitnessList)
	err := grpc.Invoke(ctx, "/protocol.Wallet/ListWitnesses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) UpdateWitness(ctx context.Context, in *protocol2.WitnessUpdateContract, opts ...grpc.CallOption) (*protocol1.Transaction, error) {
	out := new(protocol1.Transaction)
	err := grpc.Invoke(ctx, "/protocol.Wallet/UpdateWitness", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) CreateWitness(ctx context.Context, in *protocol2.WitnessCreateContract, opts ...grpc.CallOption) (*protocol1.Transaction, error) {
	out := new(protocol1.Transaction)
	err := grpc.Invoke(ctx, "/protocol.Wallet/CreateWitness", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) TransferAsset(ctx context.Context, in *protocol2.TransferAssetContract, opts ...grpc.CallOption) (*protocol1.Transaction, error) {
	out := new(protocol1.Transaction)
	err := grpc.Invoke(ctx, "/protocol.Wallet/TransferAsset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) ParticipateAssetIssue(ctx context.Context, in *protocol2.ParticipateAssetIssueContract, opts ...grpc.CallOption) (*protocol1.Transaction, error) {
	out := new(protocol1.Transaction)
	err := grpc.Invoke(ctx, "/protocol.Wallet/ParticipateAssetIssue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) ListNodes(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*NodeList, error) {
	out := new(NodeList)
	err := grpc.Invoke(ctx, "/protocol.Wallet/ListNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetAssetIssueList(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*AssetIssueList, error) {
	out := new(AssetIssueList)
	err := grpc.Invoke(ctx, "/protocol.Wallet/GetAssetIssueList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetAssetIssueByAccount(ctx context.Context, in *protocol1.Account, opts ...grpc.CallOption) (*AssetIssueList, error) {
	out := new(AssetIssueList)
	err := grpc.Invoke(ctx, "/protocol.Wallet/GetAssetIssueByAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetAssetIssueByName(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*protocol2.AssetIssueContract, error) {
	out := new(protocol2.AssetIssueContract)
	err := grpc.Invoke(ctx, "/protocol.Wallet/GetAssetIssueByName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetNowBlock(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*protocol1.Block, error) {
	out := new(protocol1.Block)
	err := grpc.Invoke(ctx, "/protocol.Wallet/GetNowBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetBlockByNum(ctx context.Context, in *NumberMessage, opts ...grpc.CallOption) (*protocol1.Block, error) {
	out := new(protocol1.Block)
	err := grpc.Invoke(ctx, "/protocol.Wallet/GetBlockByNum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) TotalTransaction(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*NumberMessage, error) {
	out := new(NumberMessage)
	err := grpc.Invoke(ctx, "/protocol.Wallet/TotalTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Wallet service

type WalletServer interface {
	GetAccount(context.Context, *protocol1.Account) (*protocol1.Account, error)
	CreateTransaction(context.Context, *protocol2.TransferContract) (*protocol1.Transaction, error)
	BroadcastTransaction(context.Context, *protocol1.Transaction) (*Return, error)
	ListAccounts(context.Context, *EmptyMessage) (*AccountList, error)
	UpdateAccount(context.Context, *protocol2.AccountUpdateContract) (*protocol1.Transaction, error)
	CreateAccount(context.Context, *protocol2.AccountCreateContract) (*protocol1.Transaction, error)
	VoteWitnessAccount(context.Context, *protocol2.VoteWitnessContract) (*protocol1.Transaction, error)
	CreateAssetIssue(context.Context, *protocol2.AssetIssueContract) (*protocol1.Transaction, error)
	ListWitnesses(context.Context, *EmptyMessage) (*WitnessList, error)
	UpdateWitness(context.Context, *protocol2.WitnessUpdateContract) (*protocol1.Transaction, error)
	CreateWitness(context.Context, *protocol2.WitnessCreateContract) (*protocol1.Transaction, error)
	TransferAsset(context.Context, *protocol2.TransferAssetContract) (*protocol1.Transaction, error)
	ParticipateAssetIssue(context.Context, *protocol2.ParticipateAssetIssueContract) (*protocol1.Transaction, error)
	ListNodes(context.Context, *EmptyMessage) (*NodeList, error)
	GetAssetIssueList(context.Context, *EmptyMessage) (*AssetIssueList, error)
	GetAssetIssueByAccount(context.Context, *protocol1.Account) (*AssetIssueList, error)
	GetAssetIssueByName(context.Context, *BytesMessage) (*protocol2.AssetIssueContract, error)
	GetNowBlock(context.Context, *EmptyMessage) (*protocol1.Block, error)
	GetBlockByNum(context.Context, *NumberMessage) (*protocol1.Block, error)
	TotalTransaction(context.Context, *EmptyMessage) (*NumberMessage, error)
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol1.Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetAccount(ctx, req.(*protocol1.Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol2.TransferContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/CreateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).CreateTransaction(ctx, req.(*protocol2.TransferContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_BroadcastTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol1.Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).BroadcastTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/BroadcastTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).BroadcastTransaction(ctx, req.(*protocol1.Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).ListAccounts(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol2.AccountUpdateContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).UpdateAccount(ctx, req.(*protocol2.AccountUpdateContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol2.AccountCreateContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).CreateAccount(ctx, req.(*protocol2.AccountCreateContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_VoteWitnessAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol2.VoteWitnessContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).VoteWitnessAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/VoteWitnessAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).VoteWitnessAccount(ctx, req.(*protocol2.VoteWitnessContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_CreateAssetIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol2.AssetIssueContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).CreateAssetIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/CreateAssetIssue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).CreateAssetIssue(ctx, req.(*protocol2.AssetIssueContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_ListWitnesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).ListWitnesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/ListWitnesses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).ListWitnesses(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_UpdateWitness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol2.WitnessUpdateContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).UpdateWitness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/UpdateWitness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).UpdateWitness(ctx, req.(*protocol2.WitnessUpdateContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_CreateWitness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol2.WitnessCreateContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).CreateWitness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/CreateWitness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).CreateWitness(ctx, req.(*protocol2.WitnessCreateContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_TransferAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol2.TransferAssetContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).TransferAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/TransferAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).TransferAsset(ctx, req.(*protocol2.TransferAssetContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_ParticipateAssetIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol2.ParticipateAssetIssueContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).ParticipateAssetIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/ParticipateAssetIssue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).ParticipateAssetIssue(ctx, req.(*protocol2.ParticipateAssetIssueContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).ListNodes(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetAssetIssueList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetAssetIssueList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/GetAssetIssueList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetAssetIssueList(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetAssetIssueByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol1.Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetAssetIssueByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/GetAssetIssueByAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetAssetIssueByAccount(ctx, req.(*protocol1.Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetAssetIssueByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BytesMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetAssetIssueByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/GetAssetIssueByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetAssetIssueByName(ctx, req.(*BytesMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetNowBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetNowBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/GetNowBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetNowBlock(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetBlockByNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetBlockByNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/GetBlockByNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetBlockByNum(ctx, req.(*NumberMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_TotalTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).TotalTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Wallet/TotalTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).TotalTransaction(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _Wallet_GetAccount_Handler,
		},
		{
			MethodName: "CreateTransaction",
			Handler:    _Wallet_CreateTransaction_Handler,
		},
		{
			MethodName: "BroadcastTransaction",
			Handler:    _Wallet_BroadcastTransaction_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _Wallet_ListAccounts_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _Wallet_UpdateAccount_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _Wallet_CreateAccount_Handler,
		},
		{
			MethodName: "VoteWitnessAccount",
			Handler:    _Wallet_VoteWitnessAccount_Handler,
		},
		{
			MethodName: "CreateAssetIssue",
			Handler:    _Wallet_CreateAssetIssue_Handler,
		},
		{
			MethodName: "ListWitnesses",
			Handler:    _Wallet_ListWitnesses_Handler,
		},
		{
			MethodName: "UpdateWitness",
			Handler:    _Wallet_UpdateWitness_Handler,
		},
		{
			MethodName: "CreateWitness",
			Handler:    _Wallet_CreateWitness_Handler,
		},
		{
			MethodName: "TransferAsset",
			Handler:    _Wallet_TransferAsset_Handler,
		},
		{
			MethodName: "ParticipateAssetIssue",
			Handler:    _Wallet_ParticipateAssetIssue_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Wallet_ListNodes_Handler,
		},
		{
			MethodName: "GetAssetIssueList",
			Handler:    _Wallet_GetAssetIssueList_Handler,
		},
		{
			MethodName: "GetAssetIssueByAccount",
			Handler:    _Wallet_GetAssetIssueByAccount_Handler,
		},
		{
			MethodName: "GetAssetIssueByName",
			Handler:    _Wallet_GetAssetIssueByName_Handler,
		},
		{
			MethodName: "GetNowBlock",
			Handler:    _Wallet_GetNowBlock_Handler,
		},
		{
			MethodName: "GetBlockByNum",
			Handler:    _Wallet_GetBlockByNum_Handler,
		},
		{
			MethodName: "TotalTransaction",
			Handler:    _Wallet_TotalTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}

// Client API for WalletSolidity service

type WalletSolidityClient interface {
	GetAccount(ctx context.Context, in *protocol1.Account, opts ...grpc.CallOption) (*protocol1.Account, error)
	ListAccounts(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*AccountList, error)
	ListWitnesses(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*WitnessList, error)
	ListNodes(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*NodeList, error)
	GetAssetIssueList(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*AssetIssueList, error)
	GetAssetIssueListByTimestamp(ctx context.Context, in *NumberMessage, opts ...grpc.CallOption) (*AssetIssueList, error)
	GetAssetIssueByAccount(ctx context.Context, in *protocol1.Account, opts ...grpc.CallOption) (*AssetIssueList, error)
	GetAssetIssueByName(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*protocol2.AssetIssueContract, error)
	GetNowBlock(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*protocol1.Block, error)
	GetBlockByNum(ctx context.Context, in *NumberMessage, opts ...grpc.CallOption) (*protocol1.Block, error)
	// get transaction
	TotalTransaction(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*NumberMessage, error)
	GetTransactionById(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*protocol1.Transaction, error)
	GetTransactionsByTimestamp(ctx context.Context, in *TimeMessage, opts ...grpc.CallOption) (*TransactionList, error)
	GetTransactionsFromThis(ctx context.Context, in *protocol1.Account, opts ...grpc.CallOption) (*TransactionList, error)
	GetTransactionsToThis(ctx context.Context, in *protocol1.Account, opts ...grpc.CallOption) (*NumberMessage, error)
}

type walletSolidityClient struct {
	cc *grpc.ClientConn
}

func NewWalletSolidityClient(cc *grpc.ClientConn) WalletSolidityClient {
	return &walletSolidityClient{cc}
}

func (c *walletSolidityClient) GetAccount(ctx context.Context, in *protocol1.Account, opts ...grpc.CallOption) (*protocol1.Account, error) {
	out := new(protocol1.Account)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/GetAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) ListAccounts(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*AccountList, error) {
	out := new(AccountList)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/ListAccounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) ListWitnesses(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*WitnessList, error) {
	out := new(WitnessList)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/ListWitnesses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) ListNodes(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*NodeList, error) {
	out := new(NodeList)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/ListNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) GetAssetIssueList(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*AssetIssueList, error) {
	out := new(AssetIssueList)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/GetAssetIssueList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) GetAssetIssueListByTimestamp(ctx context.Context, in *NumberMessage, opts ...grpc.CallOption) (*AssetIssueList, error) {
	out := new(AssetIssueList)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/GetAssetIssueListByTimestamp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) GetAssetIssueByAccount(ctx context.Context, in *protocol1.Account, opts ...grpc.CallOption) (*AssetIssueList, error) {
	out := new(AssetIssueList)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/GetAssetIssueByAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) GetAssetIssueByName(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*protocol2.AssetIssueContract, error) {
	out := new(protocol2.AssetIssueContract)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/GetAssetIssueByName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) GetNowBlock(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*protocol1.Block, error) {
	out := new(protocol1.Block)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/GetNowBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) GetBlockByNum(ctx context.Context, in *NumberMessage, opts ...grpc.CallOption) (*protocol1.Block, error) {
	out := new(protocol1.Block)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/GetBlockByNum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) TotalTransaction(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*NumberMessage, error) {
	out := new(NumberMessage)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/TotalTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) GetTransactionById(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*protocol1.Transaction, error) {
	out := new(protocol1.Transaction)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/getTransactionById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) GetTransactionsByTimestamp(ctx context.Context, in *TimeMessage, opts ...grpc.CallOption) (*TransactionList, error) {
	out := new(TransactionList)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/getTransactionsByTimestamp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) GetTransactionsFromThis(ctx context.Context, in *protocol1.Account, opts ...grpc.CallOption) (*TransactionList, error) {
	out := new(TransactionList)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/getTransactionsFromThis", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSolidityClient) GetTransactionsToThis(ctx context.Context, in *protocol1.Account, opts ...grpc.CallOption) (*NumberMessage, error) {
	out := new(NumberMessage)
	err := grpc.Invoke(ctx, "/protocol.WalletSolidity/getTransactionsToThis", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WalletSolidity service

type WalletSolidityServer interface {
	GetAccount(context.Context, *protocol1.Account) (*protocol1.Account, error)
	ListAccounts(context.Context, *EmptyMessage) (*AccountList, error)
	ListWitnesses(context.Context, *EmptyMessage) (*WitnessList, error)
	ListNodes(context.Context, *EmptyMessage) (*NodeList, error)
	GetAssetIssueList(context.Context, *EmptyMessage) (*AssetIssueList, error)
	GetAssetIssueListByTimestamp(context.Context, *NumberMessage) (*AssetIssueList, error)
	GetAssetIssueByAccount(context.Context, *protocol1.Account) (*AssetIssueList, error)
	GetAssetIssueByName(context.Context, *BytesMessage) (*protocol2.AssetIssueContract, error)
	GetNowBlock(context.Context, *EmptyMessage) (*protocol1.Block, error)
	GetBlockByNum(context.Context, *NumberMessage) (*protocol1.Block, error)
	// get transaction
	TotalTransaction(context.Context, *EmptyMessage) (*NumberMessage, error)
	GetTransactionById(context.Context, *BytesMessage) (*protocol1.Transaction, error)
	GetTransactionsByTimestamp(context.Context, *TimeMessage) (*TransactionList, error)
	GetTransactionsFromThis(context.Context, *protocol1.Account) (*TransactionList, error)
	GetTransactionsToThis(context.Context, *protocol1.Account) (*NumberMessage, error)
}

func RegisterWalletSolidityServer(s *grpc.Server, srv WalletSolidityServer) {
	s.RegisterService(&_WalletSolidity_serviceDesc, srv)
}

func _WalletSolidity_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol1.Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).GetAccount(ctx, req.(*protocol1.Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).ListAccounts(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_ListWitnesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).ListWitnesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/ListWitnesses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).ListWitnesses(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).ListNodes(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_GetAssetIssueList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).GetAssetIssueList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/GetAssetIssueList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).GetAssetIssueList(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_GetAssetIssueListByTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).GetAssetIssueListByTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/GetAssetIssueListByTimestamp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).GetAssetIssueListByTimestamp(ctx, req.(*NumberMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_GetAssetIssueByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol1.Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).GetAssetIssueByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/GetAssetIssueByAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).GetAssetIssueByAccount(ctx, req.(*protocol1.Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_GetAssetIssueByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BytesMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).GetAssetIssueByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/GetAssetIssueByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).GetAssetIssueByName(ctx, req.(*BytesMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_GetNowBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).GetNowBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/GetNowBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).GetNowBlock(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_GetBlockByNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).GetBlockByNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/GetBlockByNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).GetBlockByNum(ctx, req.(*NumberMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_TotalTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).TotalTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/TotalTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).TotalTransaction(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_GetTransactionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BytesMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).GetTransactionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/GetTransactionById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).GetTransactionById(ctx, req.(*BytesMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_GetTransactionsByTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).GetTransactionsByTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/GetTransactionsByTimestamp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).GetTransactionsByTimestamp(ctx, req.(*TimeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_GetTransactionsFromThis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol1.Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).GetTransactionsFromThis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/GetTransactionsFromThis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).GetTransactionsFromThis(ctx, req.(*protocol1.Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSolidity_GetTransactionsToThis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol1.Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSolidityServer).GetTransactionsToThis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.WalletSolidity/GetTransactionsToThis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSolidityServer).GetTransactionsToThis(ctx, req.(*protocol1.Account))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletSolidity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.WalletSolidity",
	HandlerType: (*WalletSolidityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _WalletSolidity_GetAccount_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _WalletSolidity_ListAccounts_Handler,
		},
		{
			MethodName: "ListWitnesses",
			Handler:    _WalletSolidity_ListWitnesses_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _WalletSolidity_ListNodes_Handler,
		},
		{
			MethodName: "GetAssetIssueList",
			Handler:    _WalletSolidity_GetAssetIssueList_Handler,
		},
		{
			MethodName: "GetAssetIssueListByTimestamp",
			Handler:    _WalletSolidity_GetAssetIssueListByTimestamp_Handler,
		},
		{
			MethodName: "GetAssetIssueByAccount",
			Handler:    _WalletSolidity_GetAssetIssueByAccount_Handler,
		},
		{
			MethodName: "GetAssetIssueByName",
			Handler:    _WalletSolidity_GetAssetIssueByName_Handler,
		},
		{
			MethodName: "GetNowBlock",
			Handler:    _WalletSolidity_GetNowBlock_Handler,
		},
		{
			MethodName: "GetBlockByNum",
			Handler:    _WalletSolidity_GetBlockByNum_Handler,
		},
		{
			MethodName: "TotalTransaction",
			Handler:    _WalletSolidity_TotalTransaction_Handler,
		},
		{
			MethodName: "getTransactionById",
			Handler:    _WalletSolidity_GetTransactionById_Handler,
		},
		{
			MethodName: "getTransactionsByTimestamp",
			Handler:    _WalletSolidity_GetTransactionsByTimestamp_Handler,
		},
		{
			MethodName: "getTransactionsFromThis",
			Handler:    _WalletSolidity_GetTransactionsFromThis_Handler,
		},
		{
			MethodName: "getTransactionsToThis",
			Handler:    _WalletSolidity_GetTransactionsToThis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}

// Client API for Database service

type DatabaseClient interface {
	// for tapos
	GetBlockReference(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*BlockReference, error)
	GetDynamicProperties(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*protocol1.DynamicProperties, error)
	GetNowBlock(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*protocol1.Block, error)
	GetBlockByNum(ctx context.Context, in *NumberMessage, opts ...grpc.CallOption) (*protocol1.Block, error)
}

type databaseClient struct {
	cc *grpc.ClientConn
}

func NewDatabaseClient(cc *grpc.ClientConn) DatabaseClient {
	return &databaseClient{cc}
}

func (c *databaseClient) GetBlockReference(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*BlockReference, error) {
	out := new(BlockReference)
	err := grpc.Invoke(ctx, "/protocol.Database/getBlockReference", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) GetDynamicProperties(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*protocol1.DynamicProperties, error) {
	out := new(protocol1.DynamicProperties)
	err := grpc.Invoke(ctx, "/protocol.Database/GetDynamicProperties", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) GetNowBlock(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*protocol1.Block, error) {
	out := new(protocol1.Block)
	err := grpc.Invoke(ctx, "/protocol.Database/GetNowBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) GetBlockByNum(ctx context.Context, in *NumberMessage, opts ...grpc.CallOption) (*protocol1.Block, error) {
	out := new(protocol1.Block)
	err := grpc.Invoke(ctx, "/protocol.Database/GetBlockByNum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Database service

type DatabaseServer interface {
	// for tapos
	GetBlockReference(context.Context, *EmptyMessage) (*BlockReference, error)
	GetDynamicProperties(context.Context, *EmptyMessage) (*protocol1.DynamicProperties, error)
	GetNowBlock(context.Context, *EmptyMessage) (*protocol1.Block, error)
	GetBlockByNum(context.Context, *NumberMessage) (*protocol1.Block, error)
}

func RegisterDatabaseServer(s *grpc.Server, srv DatabaseServer) {
	s.RegisterService(&_Database_serviceDesc, srv)
}

func _Database_GetBlockReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetBlockReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Database/GetBlockReference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetBlockReference(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_GetDynamicProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetDynamicProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Database/GetDynamicProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetDynamicProperties(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_GetNowBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetNowBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Database/GetNowBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetNowBlock(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_GetBlockByNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetBlockByNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Database/GetBlockByNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetBlockByNum(ctx, req.(*NumberMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Database_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Database",
	HandlerType: (*DatabaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getBlockReference",
			Handler:    _Database_GetBlockReference_Handler,
		},
		{
			MethodName: "GetDynamicProperties",
			Handler:    _Database_GetDynamicProperties_Handler,
		},
		{
			MethodName: "GetNowBlock",
			Handler:    _Database_GetNowBlock_Handler,
		},
		{
			MethodName: "GetBlockByNum",
			Handler:    _Database_GetBlockByNum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}

// Client API for Network service

type NetworkClient interface {
}

type networkClient struct {
	cc *grpc.ClientConn
}

func NewNetworkClient(cc *grpc.ClientConn) NetworkClient {
	return &networkClient{cc}
}

// Server API for Network service

type NetworkServer interface {
}

func RegisterNetworkServer(s *grpc.Server, srv NetworkServer) {
	s.RegisterService(&_Network_serviceDesc, srv)
}

var _Network_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Network",
	HandlerType: (*NetworkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/api.proto",
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xdd, 0x72, 0xd3, 0x46,
	0x14, 0xb6, 0x03, 0x49, 0x9c, 0x93, 0x1f, 0x92, 0xcd, 0x0f, 0x41, 0x49, 0x4a, 0x58, 0x60, 0x48,
	0x4b, 0x89, 0xc1, 0x69, 0x87, 0x52, 0x98, 0xd2, 0x18, 0x52, 0x37, 0x1d, 0xf0, 0x64, 0x84, 0x5b,
	0x66, 0xb8, 0xe9, 0xac, 0xe5, 0x45, 0x56, 0x91, 0xb4, 0xaa, 0x76, 0x4d, 0xc6, 0x97, 0xed, 0xf4,
	0xa2, 0xbd, 0x6d, 0xaf, 0x7a, 0xdd, 0x17, 0xe9, 0x3b, 0xf4, 0x15, 0xfa, 0x20, 0x9d, 0x5d, 0x49,
	0xd6, 0xca, 0x96, 0x1c, 0x48, 0x32, 0xd3, 0x2b, 0xac, 0x73, 0xce, 0x7e, 0xdf, 0xee, 0x9e, 0x6f,
	0xcf, 0x39, 0x04, 0xe6, 0x49, 0xe0, 0x54, 0x49, 0xe0, 0xec, 0x06, 0x21, 0x13, 0x0c, 0x55, 0xd4,
	0x3f, 0x16, 0x73, 0x8d, 0x4b, 0x16, 0x0b, 0x69, 0xb5, 0x15, 0x32, 0x3f, 0x72, 0x19, 0xcb, 0xca,
	0xf0, 0x84, 0xf9, 0x22, 0x24, 0x96, 0x88, 0x8d, 0x9b, 0x36, 0x63, 0xb6, 0x4b, 0xab, 0x0a, 0xc5,
	0xf7, 0x99, 0x20, 0xc2, 0x61, 0x3e, 0x8f, 0xbc, 0xf8, 0x19, 0x2c, 0xd4, 0x5d, 0x66, 0xbd, 0x31,
	0xe9, 0x6b, 0x1a, 0x52, 0xdf, 0xa2, 0x68, 0x03, 0x66, 0xda, 0xd2, 0xf2, 0xbd, 0xdf, 0xf3, 0xd6,
	0xcb, 0xdb, 0xe5, 0x9d, 0x0b, 0x66, 0x45, 0x19, 0x9a, 0x3d, 0x0f, 0x6d, 0x01, 0x44, 0xce, 0x2e,
	0xe1, 0xdd, 0xf5, 0x89, 0xed, 0xf2, 0xce, 0x9c, 0x19, 0x85, 0x7f, 0x4d, 0x78, 0x17, 0x6f, 0xc3,
	0x94, 0x49, 0x45, 0x2f, 0xf4, 0xd1, 0x1a, 0x4c, 0x85, 0x94, 0xf7, 0x5c, 0xa1, 0x20, 0x2a, 0x66,
	0xfc, 0x85, 0x1f, 0xc1, 0xec, 0xbe, 0x65, 0xb1, 0x9e, 0x2f, 0x9e, 0x39, 0x5c, 0xa0, 0x3b, 0x50,
	0x21, 0xd1, 0x27, 0x5f, 0x2f, 0x6f, 0x5f, 0xd8, 0x99, 0xad, 0x2d, 0xed, 0x26, 0xe7, 0xdb, 0x8d,
	0x03, 0xcd, 0x41, 0x08, 0xfe, 0x02, 0x66, 0x5f, 0x3a, 0xc2, 0xa7, 0x9c, 0xab, 0xd5, 0x55, 0x98,
	0x39, 0x8e, 0x3e, 0x69, 0xce, 0xf2, 0x38, 0xd2, 0x4c, 0x63, 0x70, 0x13, 0x16, 0xf6, 0x39, 0xa7,
	0xe2, 0x90, 0xf3, 0x1e, 0x55, 0x10, 0x8f, 0x00, 0xc8, 0xc0, 0x12, 0x63, 0x6c, 0x6a, 0x5b, 0x18,
	0xf8, 0x92, 0x5b, 0x35, 0xb5, 0x78, 0x5c, 0x83, 0x19, 0x75, 0x7b, 0x0a, 0xea, 0x26, 0x4c, 0xaa,
	0x9b, 0x88, 0x51, 0x2e, 0xa5, 0x28, 0xd1, 0x0d, 0x47, 0x5e, 0xfc, 0x0d, 0x5c, 0x6a, 0x85, 0xc4,
	0xe7, 0xc4, 0x92, 0x79, 0x50, 0x2b, 0xef, 0xc3, 0xac, 0x48, 0x4d, 0xf1, 0xfa, 0xd5, 0x74, 0xbd,
	0x16, 0x6f, 0xea, 0x91, 0xf8, 0x2e, 0x54, 0x9a, 0xac, 0x13, 0x9d, 0xe4, 0x06, 0x4c, 0xfa, 0xac,
	0x33, 0xb8, 0x88, 0x85, 0x74, 0xb9, 0x0c, 0x31, 0x23, 0x27, 0xde, 0x83, 0x8b, 0xf2, 0x13, 0xdd,
	0x86, 0x69, 0xd2, 0xe9, 0x84, 0x94, 0x73, 0x95, 0xa0, 0xec, 0xbd, 0x47, 0x0e, 0x33, 0x89, 0xc0,
	0xf7, 0x60, 0x3a, 0xb6, 0x21, 0x04, 0x17, 0xbb, 0x8c, 0x47, 0x59, 0x9d, 0x33, 0xd5, 0x6f, 0x69,
	0x0b, 0x58, 0x28, 0x94, 0x1c, 0x26, 0x4d, 0xf5, 0x1b, 0x2f, 0xc0, 0xdc, 0x81, 0x17, 0x88, 0xfe,
	0x73, 0xca, 0x39, 0xb1, 0x29, 0xbe, 0x06, 0xf3, 0xcd, 0x9e, 0xd7, 0xa6, 0x61, 0x6c, 0x40, 0x8b,
	0x70, 0x21, 0x15, 0x98, 0xfc, 0x89, 0x6f, 0xc0, 0x5c, 0xbd, 0x2f, 0x28, 0x4f, 0x22, 0x56, 0x60,
	0xf2, 0x2d, 0x71, 0x55, 0x56, 0x24, 0x57, 0xf4, 0x81, 0x3d, 0x98, 0x6d, 0x39, 0x1e, 0x4d, 0x82,
	0xee, 0xc2, 0x72, 0x9b, 0xda, 0x8e, 0x7f, 0xe8, 0x3f, 0x77, 0x5c, 0xd7, 0xe1, 0xd4, 0x62, 0x7e,
	0x87, 0xc7, 0xb0, 0x79, 0x2e, 0xf4, 0x31, 0x2c, 0x51, 0xbf, 0x33, 0x14, 0x3f, 0xa1, 0xe2, 0x47,
	0x1d, 0xb5, 0xbf, 0x11, 0x4c, 0xbd, 0x24, 0xae, 0x4b, 0x05, 0xb2, 0x01, 0x1a, 0x54, 0xc4, 0xa2,
	0x44, 0xa3, 0x3a, 0x35, 0x46, 0x4d, 0x78, 0xef, 0xe7, 0x7f, 0xfe, 0xfd, 0x63, 0xe2, 0x0e, 0x46,
	0xd5, 0x63, 0x05, 0x52, 0xb5, 0xa9, 0x88, 0xd5, 0xfc, 0x79, 0xf9, 0xa3, 0x57, 0x2b, 0x28, 0xc7,
	0x81, 0x7e, 0x2b, 0xc3, 0xd2, 0x93, 0x90, 0x12, 0x41, 0xb5, 0xc4, 0x23, 0x63, 0x48, 0x0f, 0xaf,
	0x69, 0x98, 0x68, 0xd2, 0xc8, 0xd7, 0x0a, 0xde, 0x57, 0xec, 0x0f, 0xf1, 0x95, 0x84, 0xc4, 0x52,
	0xa8, 0x9a, 0x82, 0xe4, 0x26, 0x36, 0x50, 0xb1, 0x1f, 0x75, 0x61, 0xa5, 0x1e, 0x32, 0xd2, 0xb1,
	0x08, 0x17, 0xfa, 0x6e, 0xf2, 0x19, 0x8d, 0xc5, 0xd4, 0x1c, 0x15, 0x02, 0x7c, 0x4b, 0xed, 0xe1,
	0x1a, 0xde, 0x4c, 0x38, 0xda, 0x09, 0x5c, 0x76, 0x1b, 0xe8, 0x2d, 0xcc, 0x49, 0x1d, 0xc7, 0x37,
	0xc7, 0xd1, 0x5a, 0x0a, 0xa5, 0x2b, 0x49, 0x3f, 0xab, 0x56, 0x49, 0xf0, 0x7d, 0xc5, 0x73, 0x0f,
	0xaf, 0x24, 0x3c, 0xae, 0xc3, 0x93, 0x1b, 0xe5, 0xf2, 0x98, 0x6b, 0x28, 0xd7, 0x85, 0x1c, 0x98,
	0xff, 0x36, 0xe8, 0x10, 0x41, 0x93, 0xcc, 0x5e, 0x1d, 0x21, 0x88, 0xfc, 0x27, 0xdd, 0xf6, 0xb6,
	0xda, 0x81, 0x81, 0x57, 0x13, 0x9a, 0x9e, 0x5a, 0x96, 0xa6, 0x5b, 0x52, 0x45, 0x79, 0x2d, 0xa6,
	0x8a, 0xfc, 0xef, 0x4d, 0x15, 0x25, 0x4e, 0xa3, 0xfa, 0x11, 0xd0, 0x77, 0x4c, 0xd0, 0xb8, 0x06,
	0x26, 0x7c, 0x5b, 0x29, 0x9c, 0xe6, 0x3d, 0x89, 0xed, 0xa6, 0x62, 0xbb, 0x8a, 0x8d, 0x84, 0xed,
	0x2d, 0x13, 0x34, 0x2e, 0xaa, 0x1a, 0xa5, 0x0b, 0x8b, 0xf1, 0xe9, 0x06, 0x05, 0x12, 0x8d, 0x2d,
	0xa5, 0x45, 0x7c, 0xd7, 0x15, 0xdf, 0x16, 0x5e, 0x1f, 0x3a, 0x9d, 0x04, 0x70, 0x24, 0x80, 0x64,
	0xeb, 0xc3, 0xbc, 0xcc, 0xfb, 0xcb, 0xa4, 0xb6, 0xbf, 0x8b, 0x5e, 0xb4, 0xde, 0x81, 0x1f, 0x28,
	0x92, 0xbd, 0xf4, 0x0a, 0xa5, 0x28, 0x06, 0x9d, 0x42, 0x0a, 0xe6, 0x32, 0xca, 0xf7, 0xa5, 0x8a,
	0x89, 0xf1, 0xf4, 0x34, 0xc6, 0xa6, 0x33, 0x29, 0x26, 0x66, 0xca, 0x28, 0xa6, 0x98, 0xea, 0x4c,
	0x8a, 0xc9, 0x52, 0x25, 0x75, 0x45, 0xa5, 0x4a, 0xa7, 0xca, 0x38, 0xde, 0x9b, 0x4a, 0xc4, 0xab,
	0x55, 0x02, 0x25, 0xd5, 0x4f, 0x65, 0x58, 0x3d, 0x22, 0xa1, 0x70, 0x2c, 0x27, 0xc8, 0xea, 0xe5,
	0x56, 0x0a, 0x99, 0x1b, 0x70, 0x12, 0xf7, 0x8e, 0xe2, 0xc6, 0x78, 0x2b, 0xe1, 0x0e, 0x52, 0x94,
	0xac, 0x7e, 0x7e, 0x80, 0x19, 0xa9, 0x03, 0xd9, 0x0c, 0x8b, 0xb5, 0x83, 0xb2, 0x4d, 0x54, 0x09,
	0xe7, 0x9e, 0xa2, 0xb8, 0x8d, 0x97, 0x74, 0x71, 0xa8, 0xe6, 0x2a, 0x45, 0xb3, 0x8c, 0x46, 0xed,
	0xe8, 0xd7, 0x32, 0x2c, 0xc9, 0xd6, 0x91, 0x1d, 0x3d, 0x8a, 0x48, 0xd7, 0xf3, 0xde, 0x8c, 0xa2,
	0x1e, 0xa9, 0xe7, 0xb2, 0x69, 0x0c, 0x4e, 0x25, 0xf9, 0x86, 0xea, 0xf9, 0x88, 0x1f, 0x05, 0xb0,
	0x96, 0xd9, 0x49, 0xbd, 0x3f, 0xa6, 0xa1, 0x15, 0xef, 0xe4, 0x43, 0xb5, 0x93, 0xeb, 0xf8, 0x83,
	0x5c, 0xa6, 0x76, 0x5f, 0x2b, 0x0b, 0xbf, 0x97, 0x61, 0x79, 0x88, 0xb2, 0x49, 0x3c, 0xaa, 0x1f,
	0x5f, 0x6f, 0xfb, 0xc6, 0xd8, 0x92, 0x81, 0x0f, 0x14, 0xf1, 0x63, 0xbc, 0x51, 0x40, 0xec, 0x13,
	0x4f, 0xa6, 0xf7, 0xd5, 0x16, 0x1a, 0x17, 0x81, 0x3c, 0x98, 0x6d, 0x50, 0xd1, 0x64, 0xc7, 0x6a,
	0x34, 0x2b, 0x4c, 0xc5, 0xf0, 0x0c, 0x87, 0x3f, 0x55, 0xf4, 0x55, 0xbc, 0xac, 0x81, 0xfb, 0xec,
	0x58, 0x4d, 0x76, 0x92, 0x76, 0x15, 0xe5, 0x79, 0x90, 0x80, 0xf9, 0x06, 0x15, 0x0a, 0xa2, 0xde,
	0x97, 0x73, 0xf4, 0x65, 0x4d, 0x58, 0xfa, 0x58, 0x34, 0xca, 0x38, 0x52, 0xa7, 0x6c, 0x2a, 0x14,
	0x68, 0xbb, 0xef, 0xf7, 0xbc, 0xa1, 0x3a, 0x95, 0xf1, 0xa1, 0x5f, 0xca, 0xb0, 0xd8, 0x62, 0x82,
	0xb8, 0x7a, 0xe3, 0x2e, 0x3a, 0x6a, 0xd1, 0x8e, 0xf0, 0x63, 0xb5, 0x81, 0x07, 0x69, 0x35, 0x16,
	0x12, 0x72, 0x68, 0x86, 0x30, 0x50, 0xa1, 0xbb, 0xf6, 0x57, 0x05, 0x16, 0xa2, 0x11, 0xea, 0x05,
	0x73, 0x9d, 0x8e, 0x23, 0xfa, 0xe8, 0x93, 0x53, 0x8c, 0x52, 0x25, 0xf4, 0xf8, 0x6c, 0x13, 0x42,
	0x09, 0x7d, 0x79, 0xc6, 0x9e, 0x51, 0x42, 0x0f, 0x4e, 0x5b, 0x35, 0x4a, 0xa8, 0x71, 0x3e, 0x35,
	0xa0, 0x84, 0x5e, 0xc0, 0xe6, 0x08, 0x50, 0xbd, 0x2f, 0x87, 0x62, 0x2e, 0x88, 0x17, 0x14, 0x6b,
	0x6b, 0x1c, 0x68, 0xe3, 0x7c, 0xea, 0x42, 0x09, 0x3d, 0x3f, 0xcf, 0xd7, 0x5e, 0x42, 0x9f, 0x9d,
	0xf2, 0xa1, 0x96, 0xd0, 0xc3, 0xd3, 0xbf, 0xb9, 0x12, 0x3a, 0x38, 0x8f, 0x97, 0x23, 0x61, 0x90,
	0x4d, 0xf5, 0xb9, 0xb9, 0xde, 0x3f, 0xec, 0x14, 0xde, 0x45, 0x41, 0x4f, 0x2b, 0xa1, 0x23, 0x30,
	0xb2, 0x30, 0x5c, 0xcf, 0xb7, 0xbe, 0x2c, 0xfd, 0x9f, 0x91, 0x71, 0x25, 0x17, 0x2d, 0xce, 0xd2,
	0x21, 0x5c, 0x1e, 0x42, 0xfc, 0x2a, 0x64, 0x5e, 0xab, 0xeb, 0xf0, 0xbc, 0x7c, 0x8f, 0x85, 0x3a,
	0x80, 0xd5, 0x21, 0xa8, 0x16, 0x2b, 0x02, 0x2a, 0xbe, 0xaa, 0xda, 0x9f, 0x13, 0x50, 0x79, 0x4a,
	0x04, 0x69, 0x13, 0x4e, 0xe5, 0x5b, 0xb1, 0xe3, 0xdc, 0xa5, 0x7f, 0x98, 0x78, 0x87, 0xb7, 0x92,
	0x5d, 0xa1, 0xd4, 0xb8, 0xd2, 0xa0, 0xe2, 0xa9, 0x2c, 0xfa, 0x8e, 0x75, 0x14, 0xb2, 0x80, 0x86,
	0xc2, 0x19, 0xf3, 0x74, 0x37, 0x52, 0xfb, 0xc8, 0xa2, 0xff, 0x4d, 0x8d, 0xb5, 0x19, 0x98, 0x6e,
	0x52, 0x71, 0xcc, 0xc2, 0x37, 0xf5, 0x7d, 0x98, 0x63, 0xa1, 0xbd, 0x2b, 0x42, 0xe6, 0xef, 0x92,
	0xc0, 0xa9, 0x4f, 0x37, 0xc2, 0xc0, 0xda, 0x3f, 0x3a, 0x7c, 0xb5, 0x63, 0x3b, 0xa2, 0xdb, 0x6b,
	0xef, 0x5a, 0xcc, 0xab, 0x4a, 0x6f, 0x02, 0x52, 0xb5, 0xc3, 0xc0, 0xba, 0x63, 0xcb, 0x59, 0x8f,
	0xf4, 0xab, 0x24, 0x70, 0xda, 0x53, 0xca, 0xb5, 0xf7, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01,
	0x30, 0x1b, 0xee, 0x58, 0x12, 0x00, 0x00,
}
